### ISSUE TITLE
Keeps endlessly seaching for a valid zip code

### ISSUE THREAD

**Issue by rhannink** [robertraaijmakers/com.trashchecker#1]
When I enter a valid zip code (gemeente Hellendoorn) the app keeps searching for the address, and does not return, never finds the zip code.

I will do some debugging tomorrow.

**Comment by robertraaijmakers** [comment]
Thanks. Currently trying to fix it, but a lot has changed in app sdk v2. Do you have a zipcode for me that I can use to test? My own isn't working, and I don't seem to be able to find one that should work.

**Comment by rhannink** [comment]
for example 7442BH (any house number will do)

**Comment by robertraaijmakers** [comment]
Hi, I fixt the API (general) errors. But your zipcode is still not working. It gives some error while retrieving data from the Gemeente Hellendoorn web API. Maybe you can look into this.

If the API call is fixt, the rest should work now (I found another working zip code for another API)

**Comment by rhannink** [comment]
Found it,

I do two https requests. It seems like the API provider is using expired or self signed certificates. Homey SDK 2.0 is more strict and does not accept this. 

adding the line `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";`

to **trashapi.js** (before the https.request) fixes this. Its not the most desirable solution but it is working for now.

**Comment by robertraaijmakers** [comment]
Submitted to the store for review :)
And I figured that any even numbers will do with the provided zip code. Uneven numbers won't work ;) But it's working now!

**Comment by rhannink** [comment]
Robert,

I checked the official website and same problem there, uneven numbers are not found ??? So problem is in the web API/database I will sent a mail to the gemeente....Thanks for your work.

**Comment by robertraaijmakers** [comment]
I think the uneven numbers have a different zip code, that's quite often the case :)

**Comment by rhannink** [comment]
You’re right ;-)
