### ISSUE TITLE
postal code not working (though it works with afvalwijzer)

### ISSUE THREAD

**Issue by tfreriks** [robertraaijmakers/com.trashchecker#10]
Please check my postal code (NL):

5247JV
House number 7 
(This is in my neighborhood, not my exact house :-) )

It works in Afvalwijzer, but not in the Homey App... any thoughts?

**Comment by robertraaijmakers** [comment]
Afvalwijzer is deprecated en toont geen ophaaldata meer. Deze zal dus niet meer ondersteund worden en wordt ook verwijderd in de nieuwe versie die over twee weken uitgerold gaat worden.
