### ISSUE TITLE
Verkeerd verwerken van API data voor RD4 Afvalwijzer

### ISSUE THREAD

**Issue by stofferr** [robertraaijmakers/com.trashchecker#100]
Since a few months, the app does not give me any reminders anymore.
I have linked with RD4 and the app indicates I have a valid address.
In the settings info inside the app I can see pickup dates for various kinds of trash, for example today and tomorrow.
However the flow cards don’t allow me to show any sensible reminders.
As an example, I trigger every day, filter on ‘trash to collect Tomorrow / Any type’ and then post a notification. This does not delivery any results anymore.
When I chat with Homey, the device indicates the next trash is collected in 366 days , where, according to the data in the setup page of the App, today and tomorrow (e.g. 17.9.2020 and 18.9.2020) GFT and PMD is collected.

I tested the app by manually adding tomorrow’s date.

When the date is added manually, the date format is YYYY-MM-DD but my automatic RD4 delivered data is DD-MM-YYYY format.

When tomorrow’s date is recorded in the debug info as “2020-09-22” then the App works.
When tomorrow’s date is recorded in the debug info as “22-09-2020” then the App does not work.

**I suspect the date format is the cause of the issue.**

**Comment by robertraaijmakers** [comment]
You are absolutely correct. This issue is fixed in the beta version of the app. See #94. But you have to be on Homey 5.0 because I upgraded the app to be compliant with Homey 5.0 and the new developer standards.

**Comment by stofferr** [comment]
Thanks! 

⁣Met vriendelijke groet,
Roger Stoffers ​
