### ISSUE TITLE
Tags hebben een vreemde inhoud

### ISSUE THREAD

**Issue by WesRos** [robertraaijmakers/com.trashchecker#101]
![Screenshot_20201217-204714_Homey](https://user-images.githubusercontent.com/8507396/102536071-5da9ec80-40a9-11eb-975d-ad1b0189ae3b.png)
De tag die iets niet zeggen over morgen, heeft het over vandaag. Bijvoorbeeld: tag "overmorgen" --> vandaag wordt niets opgehaald
Ik zit verwachten: tag "overmorgen". --> overmorgen wordt niets opgehaald

**Comment by robertraaijmakers** [comment]
Hi,

In the Settings page of the Trashcan Reminder App you can fully customize the settings of the tags.
You can dynamically adjust the sentence by using things like __time__ and __type__ as placeholders. By selecting the dropdown on the settings page you can see how the labels turn out.

![image](https://user-images.githubusercontent.com/1773099/102537977-f9d4f300-40ab-11eb-971c-10deac4421d7.png)
