### ISSUE TITLE
Tekst bij label "morgen opgehaald" 

### ISSUE THREAD

**Issue by rarev** [robertraaijmakers/com.trashchecker#104]
Tekst klopt niet. Er staat "wordt vandaag opgehaald" maar moet zijn "wordt morgen opgehaald"

**Comment by rarev** [comment]
Bij label "overmorgen opgehaald" geldt dit ook

**Comment by robertraaijmakers** [comment]
Zie ook #101 .
De inhoud van de tags is volledig zelf in te vullen naar wens via de settings pagina van de app.

**Comment by robertraaijmakers** [comment]
Closed due to inactivity.
