### ISSUE TITLE
Afvalwijzer klopt niet

### ISSUE THREAD

**Issue by susannahilberdink** [robertraaijmakers/com.trashchecker#105]
Goedenavond,

de afvalwijzer klopt helaas niet.
In Homey geeft hij de melding plastic bij pmd, pmd bij een plastic container.

![F4B59603-5417-4859-A16F-838F8E8957F5](https://user-images.githubusercontent.com/52762330/106062325-e9765600-60f6-11eb-9f49-1156471e3e15.png)
![F1C07BA9-8E10-4F5A-B3BF-FB8CD49F6B17](https://user-images.githubusercontent.com/52762330/106062291-debbc100-60f6-11eb-97ba-8b0cefdaef13.png)

**Comment by robertraaijmakers** [comment]
Beste, 

PMD is plastic, metaal en drinkcartons. De meeste afvalbedrijven, zoals de uwe, geven PMD dus aan als de afvalcontainer. Zoals ook uit de screenshots te zien wordt PMD op 1 feb opgehaald. Dit is zowel te zien in het screenshot van de afvalwijzer als de debug van Homey.

Volgens mij klopt het dus?

Als de melding zelf niet klopt, dan kan dat aangepast worden in het setting menu. Hier kan je zelf de labels instellen namelijk.

**Comment by susannahilberdink** [comment]
Klopt. Op 1 februari pmd.

maar niet op 28-1.

op 28-1 zegt Homey dus dat pmd gehaald wordt. Maar zoals in de afvalwijzer app te zien is, betreft dit retour stoffen en geen pmd

**Comment by robertraaijmakers** [comment]
Ah, zo, wat zijn retourstoffen? Is dat restafval? Of nog een andere categorie?

**Comment by susannahilberdink** [comment]
Retourstoffen is idd iets anders en idd een andere categorie.

voor de volledigheid even foto’s bijgevoegd. Maar vanwege deze verwarring vermoed ik dat dit daardoor verkeerd doorgegeven wordt?!


![Uploading 0EF4F273-0F43-4BFC-B246-1827F383CBA6.png…]()

**Comment by susannahilberdink** [comment]
![C61D4D10-BB41-4765-A231-131F6C64041D](https://user-images.githubusercontent.com/52762330/106115392-063f7780-6151-11eb-8151-18ba7b250990.png)

**Comment by robertraaijmakers** [comment]
Ik denk dat het beste is als ik hem dan onder textiel log. Dan kan je zelf altijd de melding aanpassen naar een melding die past bij dit type afval.

Heb je een postcode + huisnr voor mij als voorbeeld (die ong. dezelfde resultaten teruggeeft), zodat ik kan testen en aanpassen?

**Comment by susannahilberdink** [comment]
Dat is prima hoor. 

Jawel hoor, 9681TP 5

**Comment by robertraaijmakers** [comment]
Will be supported under "textiel" in update 3.0.2. Compatible with Homey version 5.0. Will try to release it somewhere this week as beta.
