### ISSUE TITLE
Geavanceerde afvaldata invoer error

### ISSUE THREAD

**Issue by Paises-Bajos** [robertraaijmakers/com.trashchecker#106]
Hi,

in the field Geavanceerde afvaldata invoer is by default some text:
{
           "GFT": [],
When I press "sla alles op" I get an error:
SyntaxError: Unexpected end of JSON input

If I clear all data in the field and then press "sla alles op" I ge the same error?

Version 2.8.2
Android 8.0

Where do I go wrong?

Regards,
Ad

**Comment by robertraaijmakers** [comment]
The default text should be complete. But seems some text is missing. Can you try to save it when only {} is in the field?

**Comment by Paises-Bajos** [comment]
Robert,

That did it, the field is filed with data and no error.
Thanks.




  [Image]




Regards,

Ad Bakker
Verzonden met Nokia 3310

________________________________

**Comment by robertraaijmakers** [comment]
I found the bug, will be resolved in next version. Yours will now stay "{}" since you saved the value. But for new installs (and people who haven't edited their settings yet) the correct basic values will be entered in the field.
