### ISSUE TITLE
Suez afval lijkt niet meer te kloppen

### ISSUE THREAD

**Issue by iAmRenzo** [robertraaijmakers/com.trashchecker#108]
Sinds 2021 lijkt de plugin niet meer te kloppen. In 2020 werd het PMD/plastic opgehaald in de even weken, in 2021 in de oneven weken. Of elke week (geen idee). Ik krijg alleen nog een melding in de even weken.
Het valt me nu echt op omdat ik zeker weet vorige week het aan de straat gezet te hebben (en het werd opgehaald) én nu rijd de wagen ook voorbij. Op Suez staat inderdaad dat ze elke week langs komen.

Is de plugin stuk?

**Comment by robertraaijmakers** [comment]
De afkorting voor maart is blijkbaar mrt ipv mar (wat opzich logisch is). Vandaar dat hij deze maand stuk is gegaan.
Zag dat ze ook ondersteuning hebben voor Textiel, dus deze categorie meteen toegevoegd.

Fix komt in een volgende versie mee.

**Comment by iAmRenzo** [comment]
Hmm, dat is grappig.
Maar hij deed het eerder dit jaar ook niet. Ik ga er vanuit dat het in 2021 wekelijks is (ipv 2-wekelijks).

Oeh, top! :)

**Comment by robertraaijmakers** [comment]
Hier kan je kijken met je eigen postcode + huisnr wanneer ze komen: https://inzamelwijzer.suez.nl/
Als daar 2-wekelijks staat, zal de app straks (nadat de fix live is) dit overnemen.

**Comment by iAmRenzo** [comment]
I know. Daar staat het hele jaar (2021) al wekelijks maar de app geeft alleen nog maar 2-wekelijks aan, zoals het in 2020 was. Ik krijg in de even weken een melding (dat was in 2020 ook zo). Dus ergens klopt er iets niet. Want ik zou dus al het hele jaar 2021 elke week een melding moeten hebben (behalve maart, zoals je hierboven zegt).

Overigens, wordt bij ons PMD opgehaald maar moest ik Plastic in Flows gebruiken.

**Comment by robertraaijmakers** [comment]
Versie 3.0.3 is nu voor approval naar Athom gestuurd. Als zij hem goedkeuren zit deze fix erin. Ik raad je aan daarna even via de settings een update te doen van je postcode + huisnummer en ook even naar de "debug" informatie (en mogelijk je flows) te kijken. 

Als je hem al eerder wilt testen kan dat door de beta versie te installeren via: https://homey.app/nl-nl/app/com.trashchecker/Afval-Herinnering-2.0/test/

Meer informatie:
- Debug: https://robertraaijmakers.github.io/com.trashchecker/settings.html
- Flow: https://robertraaijmakers.github.io/com.trashchecker/flow-examples.html

Misschien ten overvloede, maar dit werkt allemaal alleen maar als je op Homey V5 draait. Op de "oude" Homey versie is er wel meer stuk in de app waardoor deze niet betrouwbaar werkt.
