### ISSUE TITLE
Debug information: are these dates?

### ISSUE THREAD

**Issue by iAmRenzo** [robertraaijmakers/com.trashchecker#110]
The other issue was closed, but there is something. I updated the app, reentered my address. But there is something funny with the debug information... if these represent dates that is.

![IMG_1060](https://user-images.githubusercontent.com/1183790/109946074-22967d00-7cd8-11eb-8727-e0bc12686e90.jpeg)

**Comment by robertraaijmakers** [comment]
Sorry, my bad. I changed something last minute and didn't verify if the dates were parsed correctly.
The 15 should be 03 (for march). New version is submitted, will be published soon I guess.

**Comment by iAmRenzo** [comment]
I thought so, no problem.
Or... we should make a name for the 15th month! :)

**Comment by robertraaijmakers** [comment]
Nieuwe versie is uitgerold, werkt het nu wel weer?

**Comment by iAmRenzo** [comment]
Ja! Super, de data kloppen nu. Dank u! :)
