### ISSUE TITLE
Problems with days

### ISSUE THREAD

**Issue by henkbart** [robertraaijmakers/com.trashchecker#112]
Hello,
Since the new version i got a problem.
I check if there is some garbage collection for the next day. So i got a warning the day before they collect it.
That always worked good, until the update.
It now only works for the settings with today. Not for tomorrow.

Please can you check this.

Henk

**Comment by robertraaijmakers** [comment]
Hi Henk,

To help you I need some additional information.

Which API are you using?
Can you provide a example postalcode + housenumber that gives a valid response?
How are you flows configured?
Are the dates in the debug section correct? (under settings)

Some examples and information can be found here: https://robertraaijmakers.github.io/com.trashchecker/

**Comment by henkbart** [comment]
Hello,

I am using version 3.0.3 of your app.
Homey version 5.0.0

My postcode is 7326 RK 305 and that gives a valid respond
Also the debug information is valid.

Here is a picture of the one of the flows i use to set a variable and 
that is used in other flows.


This always worked, until the newerst version.
Now i only got this true when it is TODAY that the afval is being 
collected.

That is the problem

Henk

------ Original Message ------
From: "Robert" ***@***.***>
To: "robertraaijmakers/com.trashchecker" 
***@***.***>
Cc: "henkbart" ***@***.***>; "Author" 
***@***.***>
Sent: 18-3-2021 11:23:52
Subject: Re: [robertraaijmakers/com.trashchecker] Problems with days 
(#112)

**Comment by henkbart** [comment]
![2021-03-18-FireShot Pro Screen Capture #2452 - 'Homey van Henk' - my_homey_app_homeys_5cd18ec289a98d1caf5f36e4_flows_56bd4b0b-de9c-4c7d-8e52-3fd76f876](https://user-images.githubusercontent.com/54221226/111614381-d3744000-87df-11eb-8b3c-50c603f63b79.png)

**Comment by robertraaijmakers** [comment]
I think I have a suspicion why the update to V5 broke it. Under the hood Athom refactored everything to run in UTC. This means that your flow (00:05) is actually running at 23:05... which means, tomorrow, is not yet tomorrow yet.

Can you verify this by either: changing it to "the day after tomorrow" or by executing this flow at around 2:05?

Thanks!

In the meantime I will try to see if I can somehow determine what the actual local time is of the Homey that is executing the flow...

**Comment by henkbart** [comment]
Hello,

I have changed the time in the flows to 02:05 TO check if that works.
But the strange thing is, that i have flows that starts on 10:00 and 
they work fine at 10:00 local....
I will keep you informed

Henk

------ Original Message ------
From: "Robert" ***@***.***>
To: "robertraaijmakers/com.trashchecker" 
***@***.***>
Cc: "henkbart" ***@***.***>; "Author" 
***@***.***>
Sent: 18-3-2021 17:05:48
Subject: Re: [robertraaijmakers/com.trashchecker] Problems with days 
(#112)

**Comment by robertraaijmakers** [comment]
Yeah, if you have triggers, they will work fine because Homey corrects that. But that doesn't apply to the code written in this app. If you execute this flow at 10, then it should work as well. I will see if I can check the developer guide on how to correct time based on local Homey time.

**Comment by henkbart** [comment]
Hello,

When i started the flows on 02:05, then it works again.
So the problem is clear.
It has to be the UPC time. 
For me, it works now again.

Henk

**Comment by robertraaijmakers** [comment]
Thanks, good to know!
I found the documentation as well, now to figure out how to use it ;)
https://apps-sdk-v3.developer.athom.com/ManagerClock.html

**Comment by robertraaijmakers** [comment]
https://homey.app/nl-nl/app/com.trashchecker/Afval-Herinnering-2.0/test/
