### ISSUE TITLE
"Once every 4 weeks"

### ISSUE THREAD

**Issue by Timbelgium** [robertraaijmakers/com.trashchecker#119]
I cant get this to work. The paper is collected every 4 weeks on wednesday, but the app keeps pushing the date.  For example, it was this week 17th (set as first time/date), but at the bottom of the app shows it will be picked up on the 28th and from than on every 4 weeks.

**Comment by robertraaijmakers** [comment]
Hi, sorry for the late reaction. This is indeed some weird bug when generating the every four weeks feature. I will look into it.

**Comment by robertraaijmakers** [comment]
I will need some more time. Currently I am without a Homey device myself to test (for the next 10 months at least). I will try to see if I can reproduce this with some unit tests, but it will take a while before I have time again.

**Comment by robertraaijmakers** [comment]
Closed due to inactivity and this should be resolved by the published fix.
