### ISSUE TITLE
Afval herrinering

### ISSUE THREAD

**Issue by gerbenf1** [robertraaijmakers/com.trashchecker#120]
Hello i have problems with the app.

when i fill in zip code it says
Dit adres wordt niet ondersteund.

I live in Wierden and use twente milieu

**Comment by robertraaijmakers** [comment]
API is gewijzigd. Deze wijziging is nu verwerkt in de app. Nieuwe versie (3.0.11) waarin deze fix zit zou uitgerold moeten worden binnenkort.
