### ISSUE TITLE
App keeps crashing. Homey 6. 1

### ISSUE THREAD

**Issue by Hmvink** [robertraaijmakers/com.trashchecker#121]
If you need more info please let me know.

**Comment by robertraaijmakers** [comment]
Yes, please give me more information.

**Comment by Hmvink** [comment]
Hoi Robert, zeg maar wat je nodig hebt 😉

Op wo 5 mei 2021 08:53 schreef Robert ***@***.***>:

**Comment by robertraaijmakers** [comment]
Hi, graag zoveel mogelijk informatie. Denk daarbij aan:
- Versienummer Homey;
- Taalinstelling Homey;
- Welke versie van de Thrashcan App gebruik je;
- Welke actie onderneem je waarbij hij vastloopt (welke stappen, waarden e.d.);
- Als die actie reproduceerbaar is, dan kan je eventueel een crash report verzenden;
- Wat was het verwachte resultaat bij de ondernomen actie.

Ik verwacht dat het een vrij specifiek probleem is, omdat anders mijn mailbox overstroomd zou zijn met crash reports, dus hoe meer informatie des te beter het scenario na te spelen is.

**Comment by Hmvink** [comment]
Hoi Robert,

ik heb de App nogmaals herstart en nu werkt  hij wel goed. Loos alarm dus!
Prima App waar ik veel plezier aan heb!

Groet,

Hans Maarten Vink

Op wo 5 mei 2021 om 09:47 schreef Robert ***@***.***>:

**Comment by robertraaijmakers** [comment]
Hi Maarten, dankjewel, fijn dat het weer werkt!
