### ISSUE TITLE
Mijn postcode en adres worden herkend maar de kalender voor "de Meerlanden"  wordt niet opgehaald en weergegeven bij de debug informatie. 

### ISSUE THREAD

**Issue by Hmvink** [robertraaijmakers/com.trashchecker#123]
Ben benieuwd of je kunt vinden wat het is. Zo'n handige app!

**Comment by robertraaijmakers** [comment]
Hi, heb je wat meer informatie voor mij? Zoals:
- Welke versie van Homey gebruik je?
- Welke versie van de Afval app heb je geinstalleerd?
- Heb je een voorbeeld postcode + huisnummer?
- Heb je een screenshot van de instellingen pagina (staat b.v. alles op "API")

**Comment by Hmvink** [comment]
Hoi Robert,

ik ben er inmiddels uit!
Beetje stom van mij, maar ik had alles nog op n.v.t. staan ipv. volgens api
🤣

Groet,

Hans Maarten


Op ma 17 mei 2021 21:54 schreef Robert ***@***.***>:
