### ISSUE TITLE
Afvalkalender ACV

### ISSUE THREAD

**Issue by Bozo29** [robertraaijmakers/com.trashchecker#125]
Dear Robert,
This app has work perfectly for me, but now it doesn't work anymore.
When I choose "Afvalkalender ACV" with my zipcode and housenumber now it says "dit adres wordt niet ondersteund".
In the past it all works well.

**Comment by rjoomen** [comment]
Ik heb hetzelfde probleem. Het blijkt dat de ACV ook over is van Ximmio `wasteprod2api `naar `wasteapi` (zie ook #117).

Ik heb dit gecontroleerd voor een random adres in iedere gemeente waar ACV actief is (Ede, Renkum, Renswoude, Veenendaal, Wageningen).

Hier het adres van het gemeentehuis van Ede als voorbeeld:

`curl -s 'https://wasteapi.ximmio.com/api/FetchAdress' -H 'content-type: application/json;charset=UTF-8' --data-raw '{"companyCode":"f8e2844a-095e-48f9-9f98-71fceb51d2c3","postCode":"6711DD", "houseNumber": "4", "houseLetter":""}' | jq`

**Comment by robertraaijmakers** [comment]
Dank voor de pull request! Deze is verwerkt en zojuist is versie 3.0.12 gepubliceerd als test versie. Over een week, als er geen grove fouten van de test gebruikers binnen stromen. Zal de versie publiekelijk beschikbaar komen. De versie kan getest worden: https://homey.app/a/com.trashchecker/test/

**Comment by rjoomen** [comment]
Ik kan bevestigen dat ACV weer werkt. Toevoegen van het adres was begin deze week al gelukt, en zojuist een melding binnengekregen voor afval overmorgen.

Dankjewel voor de snelle update.
