### ISSUE TITLE
afval app api werkt niet inclusief oplossing

### ISSUE THREAD

**Issue by Zathrasss** [robertraaijmakers/com.trashchecker#126]
De afval app api werkt niet meer in de huidige versie. De reden hiervoor is dat er een redirect terugkomt op de http call. 

Als de code aangepast wordt naar: https.get voor deze api functioneerd de app weer.

**Comment by robertraaijmakers** [comment]
Beste, versie 3.0.12 is zojuist gepubliceerd en beschikbaar als test versie. Hierin is de Afval App fout in opgelost. Als de test periode (ongeveer een week) geen grove fouten oplevert zal ik de app publiceren naar productie.
