### ISSUE TITLE
App stopped working

### ISSUE THREAD

**Issue by rvdeijk** [robertraaijmakers/com.trashchecker#130]
@robertraaijmakers 
I see in my timeline that the app sometimes stops working and it mentions that the developer is notified.
Any Idea what goes wrong? I am using version 3.0.12
Here also a report: fda28fe2-655e-4ffb-8541-44c8744c6c54

I also noted that homey is offline at that time. The app can't reach homey. After a reboot of homey then the last thing on the timeline is this a message that this app stopped working

Here screenshot of this morning:
![IMG_20211014_064901](https://user-images.githubusercontent.com/35557458/137253928-2207bdde-7b24-46d6-bd11-56b60d96eab7.jpg)
![IMG_20211014_065004](https://user-images.githubusercontent.com/35557458/137254025-447bafd5-ffd9-49a3-aa65-cb197d92d734.jpg)

**Comment by robertraaijmakers** [comment]
Closed due to inactivity. Please re-open if issue still persists.
