### ISSUE TITLE
Calculated dates one week off

### ISSUE THREAD

**Issue by Ossiiris** [robertraaijmakers/com.trashchecker#132]
Dear Robert,

loving the app but having an issue with the calculation of the future dates based on the manual input. Have noticed/struggled with it a few times, Using version 3.1.1 but it was the same in the previous version. 

1) some weeks ago I set the right frequency for the different garbage types. Double checked the dates in the debug secion and they were all good. However, after one cycle suddenly the "rest" garbage is suddenly one week off.
2) when I try to reset the dates, the dates remain one week off. Tried to set different frequencies, save and then reset to the right frequencies, restarted the app etc both the calculated dates were still off.

These are the settings in the app:
![image](https://user-images.githubusercontent.com/35746327/138935091-09216eff-8daa-47a4-bac7-02d5eec6bb20.png)

No additional dates entered:
![image](https://user-images.githubusercontent.com/35746327/138935223-8b69fdba-7b88-4f7e-b517-6a6907a8dd73.png)

These are the dates calculated by the app:
![image](https://user-images.githubusercontent.com/35746327/138935424-f30de2f3-fccf-434b-86b0-99b8f1edef9c.png)
![image](https://user-images.githubusercontent.com/35746327/138935492-68f988e1-3c56-4cf3-a09c-56ada43e5ba4.png)

As you can see "rest" should start on 03-11-21 => 10/11 is calculated
PMD should start on 10-11-21 => 03-11-21 is calculated

At first I thought the "rest" and "PMD" dates were switched around, but that does not seem the case.

Any help is appreciated. Let me know if I can do something.

**Comment by robertraaijmakers** [comment]
This should be fixed in version 3.1.3.

**Comment by Ossiiris** [comment]
Dear Robert, dates look good now. Thank you.
