### ISSUE TITLE
Afvalkalender

### ISSUE THREAD

**Issue by gerbenf1** [robertraaijmakers/com.trashchecker#136]
Hallo,

krijg de afvalkalender niet aan de gang.

zit bij twentemilieu.
Alles ingevuld en geeft aan adres gevonden.

Heb flow gemaakt met een bepaalde tijd 
En als er morgen ieta opgehaald wordt zeg…

Maar als de ingestelde tijd bereikt wordt gebeurt er niets.

ook niet met testen wordt de flow niet gestart.

**Comment by robertraaijmakers** [comment]
Beste @gerbenf1 ,

Vervelend om te horen dat je de app niet goed aan de praat krijgt.
Om je beter te kunnen helpen zou het mij enorm helpen als je wat screenshots kan plaatsen van het (volledige) settings scherm (je adresgegevens mag je weglaten), de verschillende stappen in je flow en eventueel het resultaat wat je te zien krijgt nadat je de flow getest hebt.

Hopelijk kan ik je dan helpen bij het instellen.

Je kan ook even kijken naar https://robertraaijmakers.github.io/com.trashchecker/flow-examples.html
Misschien dat die pagina je helpt.

Mvg, Robert

**Comment by gerbenf1** [comment]
﻿Hier de fotos

Testen lukt nu niet omdat er morgen niks in de planning staat


M.v.g Gerben

**Comment by robertraaijmakers** [comment]
@gerbenf1 ik denk dat er iets mis is gegaan bij het versturen/plaatsen van de foto's. Kunt u het nog eens proberen?

**Comment by gerbenf1** [comment]
M.v.g Gerben
