### ISSUE TITLE
Circulus is (weer) gestopt met werken

### ISSUE THREAD

**Issue by henkbart** [robertraaijmakers/com.trashchecker#138]
Hello,
Sorry but again the Circulus is not working anymore. He did not recognize my postcode (7326RK 305).
I hope you can takle a look at this.

Thank You.

Henk Bartels

**Comment by robertraaijmakers** [comment]
Fixed in version 3.1.5 with help of @XeroxQ !

**Comment by XeroxQ** [comment]
You're welcome!

**Comment by XeroxQ** [comment]
Maybe the in-app name should be changed to Circulus instead of Circulus-Berkel, since it now works for all Circulus.
