### ISSUE TITLE
[App Crash] Cannot read property 'execute' of undefined

### ISSUE THREAD

**Issue by Veldkornet** [robertraaijmakers/com.trashchecker#14]
Using 2.3.0 [Beta], The app crashed immediately after update and won’t start. 

This is the stack trace:

/app.js:591
			result['execute'](postcode,homenumber,country,
			      ^

TypeError: Cannot read property 'execute' of undefined

**Comment by Veldkornet** [comment]
I should add that the app now doesn’t start at all...

**Comment by Keverjeroen** [comment]
Over here the app isn't working too.

Error:

```
/app.js:591
result['execute'](postcode,homenumber,country,
^

TypeError: Cannot read property 'execute' of undefined
at TrashcanReminder.updateAPI (/app.js:591:10)
at TrashcanReminder.onUpdateData (/app.js:408:9)
at TrashcanReminder.onInit (/app.js:42:8)
at fs.stat.i (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/SDK.js:1:3295)
at FSReqWrap.oncomplete (fs.js:153:5)

Exit code: 1
Exit signal: null
```

**Comment by robertraaijmakers** [comment]
Fixt the crash in latest build.

**Comment by robertraaijmakers** [comment]
Should all work now. Beta submitted in App Store.
