### ISSUE TITLE
Can You Add Nissewaard to the app

### ISSUE THREAD

**Issue by Jacdoor** [robertraaijmakers/com.trashchecker#140]
https://reinis.ximmio.com/modules/9dc25c8a-175a-4a41-b7a1-83f237a80b77/sitekalender/

**Comment by Jacdoor** [comment]
Is Het mogelijk dat je Reinis toevoegd tot de app

**Comment by PeterKawa** [comment]
Qoute "You can add new cities yourself, but requests to add new cities aren’t honoured. If you wish to contribute to the project (for example by adding support for a city). I would advise you to take a look at this explanation: https://robertraaijmakers.github.io/com.trashchecker/developer-guidelines.html "

**Comment by robertraaijmakers** [comment]
It should be available now in the test version: https://homey.app/a/com.trashchecker/test/

**Comment by Jacdoor** [comment]
Bedankt ik ga hem testen

Op zo 24 apr. 2022 14:05 schreef Robert ***@***.***>:

**Comment by Jacdoor** [comment]
Als ik in de app een postcodecheck doet geselecteerd op reinis doet hij
niks hij blijf adres checken aangeven

Op wo 27 apr. 2022 13:44 schreef Jacco Doornink ***@***.***>:

**Comment by Jacdoor** [comment]
Heb hem werkend op versie 7.3.0

Op wo 27 apr. 2022 14:29 schreef Jacco Doornink ***@***.***>:

**Comment by robertraaijmakers** [comment]
Denk dat je de Homey new release candidate bedoeld?
De versie van de trash app zou versie 3.1.13 moeten zijn, die is gisteren naar public gezet en zou Nissewaard (Reinis) ook toe moeten voegen. Mochten er nog issues zijn laat maar weten, voor nu sluit ik deze.
