### ISSUE TITLE
Circulus-Berkel is not working annymore

### ISSUE THREAD

**Issue by GitMike1233** [robertraaijmakers/com.trashchecker#144]
Thanks for supporting the app.
I did the update to 3.1.13 and that was not good. My app did not work anymore.
I have updated to the test version 3.1.14 and now is my adress not found.
With version 3.1.5 it was working fine.
Can you see what is wrong?
Restart of the app didn't help.
Afvalkalender Circulus-Berkelland (NL) 

Thanks.

**Comment by robertraaijmakers** [comment]
Hi @GitMike1233 ,

I need a little bit more information. As I understand with the latest test version the API and address are found again. So what is the actual issue now with the latest test version?

One thing to check if your Homeys own software is on the latest version. There have been some breaking software updates in the Homey core so be sure you are on the latest stable Homey version.

**Comment by GitMike1233** [comment]
Thanks for your answer.
This morning I thought I did forget something.
The thing is, I am not on the latest Homey firmware,  7.4. 1. I am still on 7.3.0.
Because there were a few apps that were not ready for 7.4.1.
I will have a look if they are already supported,  then I wil update.
The message for now was, " the adress is unknown".
But I wil update Homey with 7.4.1
Thanks.

**Comment by GitMike1233** [comment]
Hallo,

I still get the answer that the adress is unknown.
But the link on you're page https://robertraaijmakers.github.io/com.trashchecker/
And the for Circulus-Berkel is also broken.
Can that be the problem?
Thanks.

**Comment by robertraaijmakers** [comment]
Hi Mike,

The postal code provided works when you use Homey version 7.4.1 and Trashcan Reminder 2.0 version 3.1.14.
Can you please confirm that you are on the latest version of both?

**Comment by GitMike1233** [comment]
Hi Robert,

I was still on the 7.3.0 version of Homey like I sais earlier. With the 7.4.1 were a couple of things that was not working for me. I will check that if it is still a problem.
When I go to version 7.4.1 then I think that your app also wil work again.
I saw also that you have updated the app. Nice work.
Thanks for youre work.

**Comment by robertraaijmakers** [comment]
Thanks, then my assumption was wrong when you said "I still get the answer that the adress is unknown.". I thought that you upgraded. But lets wait for the upgrade then!

**Comment by GitMike1233** [comment]
Robert,
Here I am again.
I have checked the app wit troubles and there was an solution for it.
I have updated to 7.4.1 and Homey is already running again.
And you're app also works fine. The zip code is accepted again..
Thank you.
