### ISSUE TITLE
Change textnotification

### ISSUE THREAD

**Issue by RSlegers** [robertraaijmakers/com.trashchecker#147]
If it matches the settings it generates a message, in dutch it is "Vandaag/Morgen/Overmorgen wordt de 'kleur' container opgehaald", it says "today/tommorow/ the day after tommorow the 'color' container will be collected.

I think it is a wrong text, the don't get the container but they empty it so a better dutch tekst would be "Vandaag/Morgen/Overmorgen wordt de 'kleur' container geleegd" which is "today/tommorow/ the day after tommorow the 'color' container will be emptied".

**Comment by robertraaijmakers** [comment]
Hi @RSlegers , this is why you can change the message in the settings of the Trashcan app :) you can fully customise it to your wishes.

**Comment by EnigmaJS** [comment]
De tekst in de globale tag wordt toegepast voor alle types toch?

Maar een grijze container wordt **geleegd** en PMD wordt **opgehaald**. Dus als je de ene zin juist instelt, staat de ander weer verkeerd. Het zou mooi zijn als je dit per type kan instellen.
