### ISSUE TITLE
Extra ophaaldagen

### ISSUE THREAD

**Issue by EnigmaJS** [robertraaijmakers/com.trashchecker#148]
First of all thank you for the Afvalwijzer app in Homey. 
I have a little request. Now it is not possible to notify me by Homey about extra ophaaldagen. 
afvalwijzer kent de onderstaande types. Echter “Extra gft” ontbreekt in Homey. Would be great help for me if you want to add that type to the list. 
![8640C66E-0D2E-4B96-8C3F-10952E945E4F](https://user-images.githubusercontent.com/108389502/176367567-fc1bf377-6567-4013-83d7-8ec19883202a.png)

**Comment by robertraaijmakers** [comment]
Hi @EnigmaJS,

Can you please provide a zipcode + number with which I can test this extra type?

**Comment by EnigmaJS** [comment]
Thanks in advance!



Met vriendelijke groeten,
Judith Soffers

**Comment by EnigmaJS** [comment]
9321 GZ

**Comment by robertraaijmakers** [comment]
Thanks @EnigmaJS , you can test it here: https://homey.app/a/com.trashchecker/test/

**Comment by EnigmaJS** [comment]
Tested and ok. 
The "extra gft" on 13-07 is now shown in the output. Thank you very much for your quick support!

![image](https://user-images.githubusercontent.com/108389502/176672384-195a3c6f-7d1d-46f5-8dd1-179ad610d591.jpeg)
