### ISSUE TITLE
Not any address supported

### ISSUE THREAD

**Issue by EricMB73** [robertraaijmakers/com.trashchecker#149]
Hi,
I have used this app for a while now with no issues. Until I noticed I didn’t receive any notifications anymore.
So just tried to set my postal code again, but no luck. The app accepts no postalcode at all. 

I have always used: 1141SL number 15
It works on the mijnafvalwijzer-app, but not in de homey app. 
On every postalcode I try it’s “address not supported “
I am on the latest version of the app and the latest version of Homey Pro

best regards,

Eric

**Comment by robertraaijmakers** [comment]
Released a test version: https://homey.app/a/com.trashchecker/test/, can you verify if that solves the issue and also if the dates are correct?

**Comment by JoSan-0** [comment]
Checked and is working again, thanks!
