### ISSUE TITLE
beta 2.3.2 not getting api results  or at least no postalcode is supported 

### ISSUE THREAD

**Issue by eelco2k** [robertraaijmakers/com.trashchecker#15]
I was checking the latest beta 2.3.2 but unfortunately it's not able to receive the data from any API result correctly and it's only responding with:

"Dit adres wordt niet ondersteund" 

Even when i manually open the api url (in my case: https://rd4.syzygy.eu/6269AC/20/ ) it returns the correct JSON object. but in Homey nothing works.

**Comment by robertraaijmakers** [comment]
If I run your zipcode, the debugger gives the error " Invalid Location ".

If I check the response message from the server when Homey tries to get the URL it returns a "statusCode: 500,
  statusMessage: 'Internal Server Error',".

So it's something in the API that probably wants to retrieve some special (browser) headers that Homey doesn't sent.

**Comment by eelco2k** [comment]
I tried with postman doing a get request and i am receiving a json response. And it did work before... haven't changed anything to the webservice..

**Comment by eelco2k** [comment]
it is gzip though...

**Comment by eelco2k** [comment]
found the issue. it was on the server side regarding caching and IP check
