### ISSUE TITLE
Homey advanced flow 

### ISSUE THREAD

**Issue by SolarNL** [robertraaijmakers/com.trashchecker#152]
I'm rebuilding some of my flows to 'advanced flows' in Homey. Today 'PMD' will be picked up, but when I test it, it also gives positive result for PMD tomorrow and PMD the day after tomorrow.
I tested it again in the 'normal flow' and that works like it should.

**Comment by SolarNL** [comment]
Hi @robertraaijmakers ,

It could very well be a bug from homey. This is the issue, I put a card saying; iets wordt (over)morgen opgehaald. Acoording ot the calender PMD is collected today, but tomorrow and the day after tomorrow also gives a positive result.

![image](https://user-images.githubusercontent.com/17107934/177994234-c06f591a-f9df-4d9f-a084-7a83de65c3d8.png)

If I use the same card in the normal flow, it stops the flow at that card because it is untrue.

![image](https://user-images.githubusercontent.com/17107934/177994541-d3d71f2a-e805-4b97-b07d-71f784b61d99.png)

**Comment by robertraaijmakers** [comment]
Thanks, I will have a look into it. But it might take a while due to summer holidays and some busy times ahead of me.

**Comment by KRens** [comment]
I tried a very simple scenario in advanced flows and that seems to work for "tomorrow".
I also checked overmorgen and it did not get triggered.

**Comment by robertraaijmakers** [comment]
Hi @KRens , got advanced flow in the mean time. Here the time triggers are working fine. Do you still experience some issues? I think it was probably a issue in advanced flow instead of this app.

**Comment by KRens** [comment]
> Hi @KRens, @SolarNL , got advanced flow in the mean time. Here the time triggers are working fine. Do you still experience some issues? I think it was probably a issue in advanced flow instead of this app.

It started working by itself. So I guess the developers fixed this issue meanwhile.
