### ISSUE TITLE
Spelling tekst

### ISSUE THREAD

**Issue by brembootje** [robertraaijmakers/com.trashchecker#154]
Drank kartons, verkeerd gespeld? Verder werkt de app super!! ![image](https://user-images.githubusercontent.com/86266186/185986711-6a97e7bf-1698-49a1-bc11-f96c8b0bc708.png)

**Comment by robertraaijmakers** [comment]
This is now fixed in latest test version (3.2.0): https://homey.app/a/com.trashchecker/test/
