### ISSUE TITLE
Te veel data voor restafval

### ISSUE THREAD

**Issue by JoSan-0** [robertraaijmakers/com.trashchecker#156]
Ik heb sinds een maand (of twee) een vreemd issue, namelijk dat de app aangeeft dat het restafval iedere week wordt opgehaald. 
Bij de bron (mijn AfvalWijzer) staat het wel goed (om de week).
Ik zie in de configuratie ook iets vreemds, bij de datums zie ik op de datum dat de rest WEL opgehaald, deze er 2x in staan. Op de data dat de rest NIET opgehaald wordt, staat deze er 1x in. 
screenshot maakt dat wat duidelijker. Op 2022-09-08 werd rest dus niet opgehaald. Op 2022-09-01 en 2022-09-5 wel. 
![E28D9BAF-4F1D-450F-8224-B320CE2C5FB9](https://user-images.githubusercontent.com/72399089/189207293-bc78dfb9-bea7-480c-a643-6bbef6666fef.png)

**Comment by robertraaijmakers** [comment]
Hi, heb je een voorbeeld postcode en huisnummer? Dan kan ik aan de hand daarvan kijken wat er fout gaat. Afvalwijzer heeft regio’s door heel NL en behandeld elke weer anders.

**Comment by JoSan-0** [comment]
Hi Robert,

5685HK 32 is mijn postcode. 

Groet,
Joost

**Comment by JoSan-0** [comment]
Ik zie een mogelijke oorzaak in de brondata. Ik weet niet of je voor restafval filtert op "afvaldescr" en dan op "rest", maar als dat zo is dan is dat de oorzaak. De ene week is er een "Restafval", maar iedere week is er ook "Etensresten". Dat zou ook kunnen verklaren waarom er de ene week 1 en de andere week 2 entries terugkomen in de lijst.

**Comment by robertraaijmakers** [comment]
Top! Dat is het inderdaad, waar zouden etensresten onder vallen? Is dat dan GFT?

**Comment by JoSan-0** [comment]
> Top! Dat is het inderdaad, waar zouden etensresten onder vallen? Is dat dan GFT?

Etensresten is een aparte afvalstroom bij ons, die weinig mensen gebruiken overigens. Ze mogen bij GFT maar je kunt er ook een klein emmertje voor krijgen voor alleen etensresten. Die wordt dan opgehaald in de etensresten stroom.

**Comment by robertraaijmakers** [comment]
This is now fixed with latest test version (3.2.0): https://homey.app/a/com.trashchecker/test/

**Comment by JoSan-0** [comment]
Just checked the dates in the test version and can confirm this is now solved. Thanks!
