### ISSUE TITLE
Mijnafwalwijzer gives a false when asking for pick-up date but should be true

### ISSUE THREAD

**Issue by LithiumNL** [robertraaijmakers/com.trashchecker#16]
After adding the app into homey i added my postal code into the configuration.
Made a new flow to check whenever plastic is collected, this should be true (today) but the app gives a false. After adding it manually it works fine.

The postal code is supported, checked it manually on the website.

**Comment by robertraaijmakers** [comment]
Most APIs aren't giving today as a valid pick up date when retrieving the pickup dates. This is why it doesn't work for today. You can check what dates are received by clicking on the green test after adding your ZIP code.

**Comment by LithiumNL** [comment]
I also tried to use the tomorrow settings, same result.

**Comment by robertraaijmakers** [comment]
Can you provide a bit more information? Like the pick up dates that are retrieved from the API (when you click the green text, they are shown. (like in the screenshot attached). If the dates shown there are incorrect, please give me a postal code (I will find a house number myself) to test with.

If the dates shown there are correct. Then the tomorrow settings etc. should work properly and I would like to hear what's not working as expected and what steps you took to reproduce the issue.

![image](https://user-images.githubusercontent.com/1773099/36197706-cb0a5d58-1174-11e8-8813-300416a69aee.png)

**Comment by LithiumNL** [comment]
Found the problem.
trashapis.js from line 82. It does not search for plastic and i was testing it with plastic last week ;)
That can be a future request.

``case 'plastic':
if (!fDates.PLASTIC) fDates.PLASTIC= [];
fDates.PLASTIC.push(dateStr);
break;``
