### ISSUE TITLE
Ondersteuning Afval3xbeter App

### ISSUE THREAD

**Issue by Dinky2534** [robertraaijmakers/com.trashchecker#161]
Hallo Robert,

Is het mogelijk de ondersteuning van de "afval3keerbeter" app/website toe te voegen?

Het heeft hier altijd prima gewerkt via de "mijn afvalwijzer (NL)" maar de gemeente is vanaf 2023 overgestapt naar de "afval3keerbeter"website en app.

**Comment by robertraaijmakers** [comment]
Hi @Dinky2534,

Etten-leur was blijbkaar overgestapt naar een andere provider, de nieuwe API is inmiddels geimplementeerd. Momenteel alleen nog in het test-kanaal beschikbaar. Tegen einde van de week zal hij via de normale kanalen bijgewerkt worden.

https://homey.app/a/com.trashchecker/test/

**Comment by Dinky2534** [comment]
Goedenavond Robert!

 

Super dat je Etten-Leur hebt kunnen toevoegen! Heb de beta meteen geïnstalleerd. 

Ben erg blij met deze app!

 

 

Vriendelijk bedankt!

 

 

 

Van: Robert ***@***.***> 
Verzonden: dinsdag 7 februari 2023 22:13
Aan: robertraaijmakers/com.trashchecker ***@***.***>
CC: Dinky2534 ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [robertraaijmakers/com.trashchecker] Ondersteuning Afval3xbeter App (Issue #161)

 

Hi @Dinky2534 <https://github.com/Dinky2534> ,

Etten-leur was blijbkaar overgestapt naar een andere provider, de nieuwe API is inmiddels geimplementeerd. Momenteel alleen nog in het test-kanaal beschikbaar. Tegen einde van de week zal hij via de normale kanalen bijgewerkt worden.

https://homey.app/a/com.trashchecker/test/

**Comment by Dinky2534** [comment]
Hallo Robert,

Wil even laten weten dat de update met Etten-Leur goed werkt. Heb al verschillende afval meldingen gehad. Top app!

Vriendelijke groet,

Harno



Verzonden vanaf mijn Galaxy



-------- Oorspronkelijk bericht --------
Van: Robert ***@***.***>
Datum: 07-02-2023 22:12 (GMT+01:00)
Aan: "robertraaijmakers/com.trashchecker" ***@***.***>
Cc: Dinky2534 ***@***.***>, Mention ***@***.***>
Onderwerp: Re: [robertraaijmakers/com.trashchecker] Ondersteuning Afval3xbeter App (Issue #161)


Hi @Dinky2534<https://github.com/Dinky2534>,

Etten-leur was blijbkaar overgestapt naar een andere provider, de nieuwe API is inmiddels geimplementeerd. Momenteel alleen nog in het test-kanaal beschikbaar. Tegen einde van de week zal hij via de normale kanalen bijgewerkt worden.

https://homey.app/a/com.trashchecker/test/

**Comment by Dinky2534** [comment]
Hallo Robert,

Kwam tot de ontdekking dat de afvalkalender Etten-Leur (NL) momenteel niet meer werkt. Bij de debug info in de app zie ik dat de laatst opgehaalde datum 01 augustus is. Als ik bij "Trashcan Reminder Settings" op opslaan druk krijg ik ook een foutmelding dat het adres niet wordt ondersteund (heeft na je aanpassingen in februari 2023 probleemloos gewerkt). 

Als ik op https://www.mijnafvalwijzer.nl/ mijn adres invoer wordt het adres wel gevonden.

Heb je hier een oplossing voor?

Vriendelijke groet,

Harno
