### ISSUE TITLE
Kerstboom kwam niet door

### ISSUE THREAD

**Issue by brembootje** [robertraaijmakers/com.trashchecker#164]
De melding dat de kerstboom opgehaald zou worden (Circulus) kwam niet door. Wel ingesteld via Flow(s).

App versie 3.2.0.

**Comment by robertraaijmakers** [comment]
Beste @brembootje,

Bedankt voor het bericht. Het is een beetje lastig debuggen aangezien kerst een eenmalig event is.
Wat ik zie bij Circulus is dat afhankelijk van de postcode hij wel of niet mee komt.

Kan je voor mij een screenshot maken van de flow zoals je hem ingesteld hebt?
En tevens een screenshot van het het instellingen scherm in de app (vooral het stuk onderaan - " DEBUG ") waar alle data staan is interessant. Staat daar b.v. de kerst als datum tussen?

**Comment by robertraaijmakers** [comment]
Ik heb het al gevonden, kerstbomen was voor Circulus nog niet geimplementeerd. Hij viel terug op een default, maar die wordt niet herkent in de flow. Daarom staat hij waarschijnlijk wel als datum bij de DEBUG, maar komt er geen trigger. Ik heb het nu aangepast en dan gaat het hopelijk volgend jaar wel goed ;)

**Comment by brembootje** [comment]
Hoi,Ah! Super! Had net de info verzameld. We gaan het zien volgend jaar. Bedankt! Had je nog interesse in de flow of niet? Groeten, BramOp 30 jan. 2023 om 19:27 heeft Robert ***@***.***> het volgende geschreven:﻿
Ik heb het al gevonden, kerstbomen was voor Circulus nog niet geimplementeerd. Hij viel terug op een default, maar die wordt niet herkent in de flow. Daarom staat hij waarschijnlijk wel als datum bij de DEBUG, maar komt er geen trigger. Ik heb het nu aangepast en dan gaat het hopelijk volgend jaar wel goed ;)
