### ISSUE TITLE
RMN stopped working

### ISSUE THREAD

**Issue by robertraaijmakers** [robertraaijmakers/com.trashchecker#167]
RMN switched to a new platform (Mendix) and a new mobile app. The whole API has changed and now needs 50+ API calls to request the trash dates of one month.

A new way needs to be found to effectively retrieve the trash collection dates.

https://21burgerportaal.mendixcloud.com/p/rmn/landing/

**Comment by robertraaijmakers** [comment]
See also this thread: https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/issues/382
At the moment it is not possible to use the RMN API :(

**Comment by Sjoenge** [comment]
Dat is wel balen zeg, bedankt iig voor de moeite en inzit Robert, heb toch langer dan een jaar jou app super kunnen gebruiken.

**Comment by robertraaijmakers** [comment]
Ja, is doodzonde dit. Vooral omdat RMN één van de grootste partijen is (groot gebied). Nu wordt het weer terug op de 'handmatige' invoer. Waarbij je periodes op kan geven. Vaak worden de kliko's in een vast ritme opgehaald en dat kan je dan eenmalig configureren in de settings van de app. Maar is wel minder prettig en als het een keer wijzigt dan krijg je dat niet mee.

**Comment by robertraaijmakers** [comment]
Added support for RMN again, can be tested here: https://homey.app/a/com.trashchecker/test/

**Comment by Svantie** [comment]
Also installed the latest version above here. When refreshing my 'postcode' and 'huisnummer' it says its added and the "known trash collection dates" are filled in again in the debug where it show the known trash dates of RMN for the various separated trash.
This gives me good hope!

Tnx for putting your time and effort in to this great app! Coming week we'll see if I get notifications again!☺️

**Comment by Svantie** [comment]
Just one final write-up about this issue. Yes it is fixed 🥳

As of today, I receive my notifications again. Thanks for fixing it
