### ISSUE TITLE
M'n Afvalwijzer werkt niet

### ISSUE THREAD

**Issue by Hopisushi** [robertraaijmakers/com.trashchecker#169]
Hi, 2 jaar goed gedaan, nu werkt het niet meer. Kan je mij helpen wat te doen met m'n homey?

**Comment by Hopisushi** [comment]
Ik heb n code voor diagnostic report opgevraagd
491df3a0-c621-4213-91d4-840f1dffc383

**Comment by robertraaijmakers** [comment]
Bedankt voor je melding, je valt onder regio RMN en die hebben recentelijk hun API aangepast. Zie ook openstaande issue #167. Ik kan hier helaas weinig aan doen op dit moment totdat RMN hun data weer publiekelijk beschikbaar maakt.

**Comment by Hopisushi** [comment]
Dankjewel Robert, ik had het inderdaad gelezen, wat balen! Kan ik actie ondernemen om contact op te nemen met RMN?

Cheers, Kim van Meel
________________________________
Van: Robert ***@***.***>
Verzonden: Tuesday, March 28, 2023 9:31:43 PM
Aan: robertraaijmakers/com.trashchecker ***@***.***>
CC: Hopisushi ***@***.***>; Author ***@***.***>
Onderwerp: Re: [robertraaijmakers/com.trashchecker] M'n Afvalwijzer werkt niet (Issue #169)


Bedankt voor je melding, je valt onder regio RMN en die hebben recentelijk hun API aangepast. Zie ook openstaande issue #167<https://github.com/robertraaijmakers/com.trashchecker/issues/167>. Ik kan hier helaas weinig aan doen op dit moment totdat RMN hun data weer publiekelijk beschikbaar maakt.

**Comment by robertraaijmakers** [comment]
Proberen kan altijd, ik heb zelf ook al contact gezocht met ze n.a.v. dit topic: https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/issues/382

Misschien dat het helpt als meerdere mensen hun beklag doen :)
