### ISSUE TITLE
 Homey Afval herinnering app werkt niet

### ISSUE THREAD

**Issue by MrReiplHill** [robertraaijmakers/com.trashchecker#170]
Beste, 

er is mij via een review gevraagd een issue aan te maken. Ik heb de homey pro early 19 met 8.1.3. Zoals ik het nu heb en ik ben een beginnend smarthome owner heb ik “als” het 22:00 uur is “en” gft of pmd of papier of rest word morgen opgehaald “dan” hue lamp aan op bepaalde kleur. In de afval herinnering app in homey heb ik mijn adres in de bovenste balk gezet en afval app gekozen. 

![6D92A622-8F33-4E2A-A9F5-6D8843330A17](https://user-images.githubusercontent.com/129317777/228616172-c70848ee-52e4-4c47-ada9-a876e5592d71.png)

Albast reuze bedankt!!

**Comment by robertraaijmakers** [comment]
Bedankt voor je bericht. Op dit moment werkt de afvalkalender functionaliteit van de RMN niet meer. Zie ook issue #167.
Onder welke regio / afvalbeheerder valt het adres?

Op zich lijken de instellingen die je hebt namelijk prima. Zie hieronder een voorbeeldflow.
![image](https://user-images.githubusercontent.com/1773099/228842133-03711e0a-a967-4e33-9ea1-34b8d3697110.png)

Eventuele andere tips & tricks kan je hier lezen: 
Settings: https://robertraaijmakers.github.io/com.trashchecker/settings.html
Flow examples: https://robertraaijmakers.github.io/com.trashchecker/flow-examples.html

**Comment by robertraaijmakers** [comment]
@MrReiplHill Is het inmiddels gelukt?

**Comment by MrReiplHill** [comment]
Hoi Robert,Ik heb het nu handmatig ingevoerd, en het werkt. Alleen lastig bij feestdagen zoals dit weekend, maandag word hier dus niks opgehaald maar zaterdag. Deze momenten zal ik zelf in de gaten moeten houden. Snap niet waarom het niet werkt via mijn adres in de bovenste optie als je de app configureer. Waar zou dit aan kunnen liggen?Verstuurd vanaf mijn iPhoneOp 7 apr. 2023 om 13:21 heeft Robert ***@***.***> het volgende geschreven:﻿
@MrReiplHill Is het inmiddels gelukt?

**Comment by robertraaijmakers** [comment]
Hoi @MrReiplHill 

Als je in een regio woont waar de data niet openbaar opgehaald kan worden dan is handmatig inderdaad de enige optie. In welke regio woont u / wie is het afvalophaalbedrijf?

**Comment by MrReiplHill** [comment]
Hoi Robert,Ik woon in Helmond ons afval word opgehaald door suez, ik gebruik al jaren de afval app die je ook kan kiezen in de afval app.Verstuurd vanaf mijn iPhoneOp 7 apr. 2023 om 16:54 heeft Robert ***@***.***> het volgende geschreven:﻿
Hoi @MrReiplHill
Als je in een regio woont waar de data niet openbaar opgehaald kan worden dan is handmatig inderdaad de enige optie. In welke regio woont u / wie is het afvalophaalbedrijf?
