### ISSUE TITLE
Afval kalender RMN werkt niet meer

### ISSUE THREAD

**Issue by Sjoenge** [robertraaijmakers/com.trashchecker#171]
Ik heb een diagnostics report van gemaakt via Homey: 9bd42e99-3a7e-4e3d-a7fc-3a3b2c6ebfcc

Sinds de laatste update van Homey of deze app werkt Afvalkalender RMN(NL) niet meer terwijl het zeker een jaar of meer goed heeft gewerkt.

Specs:
Afval Herinnering 2.0 v3.2.3
Homey Pro Early 2019
Homey versie 8.1.3

Wat gaat er niet goed:
Mijn flows werken niet meer terwijl die meer als een jaar goed gefunctioneerd hebben, als ik nu bij Configureer App -> pulldown menu Afvalkalender RMN(NL) waar die ook opstond, mijn postcode en huisnummer laat staan waar die ook op stond, daarna op opslaan druk, zegt die: Dit adres word niet ondersteund, wat raar is want dit heeft zoals eerder vermeld langer dan een jaar gewerkt.

Miss dat er iets is veranderd in de opzet van de website van RMN waardoor dit niet meer goed werkt of iets, maar zag ook al dat er nog iemand issue's heeft met dezelfde Homey Pro dus het zou ook aan die kant verkeerd kunnen gaan.

**Comment by robertraaijmakers** [comment]
Beste, bedankt zie ook #167 en de reactie van RMN die ik terug heb gehad.
