### ISSUE TITLE
ZRD not working any more

### ISSUE THREAD

**Issue by Barblo1986** [robertraaijmakers/com.trashchecker#172]
For a few weeks now, the trashchecker app has not been working for us. 
We fall under the region ZRD and when setting it up I get the message that my address is no longer supported! 
The app worked for years before this :) 

Does this depend on the app or is the problem in ZRD's API?

**Comment by robertraaijmakers** [comment]
I have tried a few zipcodes in Zeeland, but none of them give a result on the ZRD site?
https://www.zrd.nl/wanneer

Can you give an example postalcode + house number that gives a result on that site so I can check if anything in the Homey app is wrong, or maybe their own API is down?

**Comment by Barblo1986** [comment]
Hello, my zip code is: 4569AD 26 and in the Homey app it is not recognized (see photo). It is recognized on the ZRD website (see photo).

![image](https://github.com/robertraaijmakers/com.trashchecker/assets/74736445/d545546b-3a63-4694-9bf9-8f40b3a9dd2e)

![image](https://github.com/robertraaijmakers/com.trashchecker/assets/74736445/19c4ee66-bcfd-4631-8da5-d9804ac19ae9)

🤷🏼‍♂️

Greetings,

Steven

**Comment by robertraaijmakers** [comment]
Thanks, hun URL is aangepast. Heb hem gewijzigd. Nieuwe versie zojuist uitgerold (3.2.7). Kan je kijken of die werkt?

**Comment by Barblo1986** [comment]
![image](https://github.com/robertraaijmakers/com.trashchecker/assets/74736445/619f2c74-af67-42e1-b3be-c38e84ff46e4)

Yes, hij werkt weer! 🙂 
Bedankt
