### ISSUE TITLE
no device?

### ISSUE THREAD

**Issue by henkied** [robertraaijmakers/com.trashchecker#173]
Hello,

I downloaded trashchecker and added location data manually.

If I then want to install a new device, I don't see it anywhere

I have a homey pro early 2023 version 1.0.0.0-rc-110

Am I overlooking something?

**Comment by robertraaijmakers** [comment]
Hello @henkied,

This app doesn't have any device. You can build one (or multiple) flows to notify yourself when the trash is collected.
Please refer to this manual to figure out how you can configure the flows: https://robertraaijmakers.github.io/com.trashchecker/flow-examples.html

With kind regards,
Robert Raaijmakers
