### ISSUE TITLE
Add Best-tas

### ISSUE THREAD

**Issue by LRvdLinden** [robertraaijmakers/com.trashchecker#174]
Hi @robertraaijmakers can you add for circules berkel also the best-bag?

![image](https://github.com/robertraaijmakers/com.trashchecker/assets/77990847/5520db51-ce9e-42d1-951e-f713d9ae2c62)

**Comment by robertraaijmakers** [comment]
@LRvdLinden de best-tas kan je vinden onder het kopje "TEXTIEL". Als je daar de tekst aanpast naar wat leuks wat je wilt, dan krijg je ook een notificatie voor de best tas.

**Comment by LRvdLinden** [comment]
Top! Dank @robertraaijmakers
