### ISSUE TITLE
Next date for %anything% + Next date for %specific%

### ISSUE THREAD

**Issue by Tweaqer** [robertraaijmakers/com.trashchecker#175]
Dear Robert,
Would it be possible to create a feature where you could launch a flow to return the next date of pick-up and maybe the second or third following as well?
Ie:
- The next pick-up will be 'restafval' on Friday, August 25th (4 days from now)
- The 2nd pick-up will be 'papier' on Monday, August 28th (7 days from now)

And for specific pickups:
- The next 'GFT' pick up will be 4th of September (14 days from now)

Love your app, thanks for your efforts developing it :)
Cheers!

**Comment by robertraaijmakers** [comment]
I think this might be possible with Advanced Flows (https://apps.developer.homey.app/the-basics/flow/tokens#tokens-for-advanced-flow) but I have to look into it.

To better understand the feature, what would you do with the information? e.g. how would you use this in a flow?

**Comment by Tweaqer** [comment]
Well basicly, the idea originated from a widget I've had with HomeAssistant:
![image](https://github.com/robertraaijmakers/com.trashchecker/assets/20989897/bd1cdf00-b4eb-4c24-966e-fa1cefb87a67)

It's just handy and easy to get some kind of overview of what is coming up when. However, I do not necessarily need a widget. I could as well be sending it as a mesage over Telegram hence the request :)

**Comment by robertraaijmakers** [comment]
That is quite cool, maybe (but I don't know how) I can create some 'devices' with a nice logo/picture and the next pick-up date. Then you can add them to your devices view and see when they are picked up next...

The card might be easier, but I will have a look once I have some free time :)

**Comment by Tweaqer** [comment]
Thats a great idea actually! And thank you for looking into it and your efforts on the app so far. It saved me from forgetting to put out the bin countless times already :) Cheers

**Comment by MarcelMuxio** [comment]
Nice!

For me, the icons could be a bit more smaller. Or it would be nice that the number of items feature the number of items in a row adjusts. If you now select more than 3 items, but doesn't change the number of rows, it makes no sense.

**Comment by robertraaijmakers** [comment]
Thanks! Couldn’t make the icons smaller because then the text doesn’t fit anymore. So need the width anyway.

When you do more items without adding rows you can scroll within the widget to see the next dates! :)

**Comment by cderooij** [comment]
Very nice the new dashboard, thanks!

I like to have 4  “afvalregels” but for that it seems I need to add also an extra row.. 
But when I add an extra row I think it would be better to get them 2 by 2. 

And when possible it would be nice to add a text (papier etc.) and not only an icon, but it works for me as it is as well 😊

**Comment by robertraaijmakers** [comment]
@cderooij thanks! I was wondering about this. Do you think the width of the widget is the same for all devices? If so and I can assume that for everyone the max to show on a single line is three, I can then do two things when someone enables more lines: 
- 1. show 2 items per row (if someone has 4 container types, if someone has 5 I should do 3 and 2). 
- 2. show 3 items per row, but then (for people with 2-5 containers) it will show some duplicates.

Which one would be nicer?

**Comment by cderooij** [comment]
Hi Robert,
For me the width, with max 3 items per row, feels the same on all my devices. 

For me the option to add the next collections dates of my containers will work, and I can imagine that it looks also better than rows with less icons. 

Thanks and regards, Cor

**Comment by Tweaqer** [comment]
Really cool stuff btw, thanks for your efforts on this Robert!

**Comment by robertraaijmakers** [comment]
So I have tried to make a better version to suit most needs. This does mean that there are a lot of extra settings you can do in the widget now :)

1. You can choose if you want to disable certain types
2. You can choose if you want to show only unique types or just the most recent collected items
3. You can choose if you want to show what is collected yesterday
4. You can choose your layout style (compact or large). Where large is the original and compact is more in the style of how Moods are displayed. I think the compact is more suitable for phones, whilst the large might be better on tablets or larger screens.

Really looking for the feedback and thanks for testing! :)

p.s. if someone has a better SVG image for the PMD (or other trash types) I would be open for it. I don't like the current PMD icon which is kind of an open can. I was more looking for something like this. But can't find an svg version of it.

![image](https://github.com/user-attachments/assets/762a6096-e88a-4c4d-b1e3-26218c5a9c72)

**Comment by cderooij** [comment]
Hi Robert,
This is perfect as it is, very flexible. 
it was a little bit unclear first that I need to say 6 items to see the “double” items, but it works. 
Thanks and regards,
