### ISSUE TITLE
Resultaten van de afval herinnering 2.0 kloppen niet

### ISSUE THREAD

**Issue by RobRebel** [robertraaijmakers/com.trashchecker#176]
Goedenavond Robert,

Ik gebruikte deze app al op de Homey van 2016 naar grote tevredenheid. Nu heb ik sinds kort de Homey 2023 aangeschaft maar helaas werkt de app hier niet correct op.  De resultaten die de app geven kloppen totaal niet, ik heb ze getest op adres en handmatig.. 

Ik heb nu drie datums getest en heb een paar afbeeldingen gemaakt: 
2 van de basis instellingen van de app, 
1 van de werkelijke datums die gepland zijn 
3 van de geteste resultaten per datum.

Ik hoop dat je hier na wil kijken, iets mee kunt en het probleem kan oplossen.  Want ik zou graag deze app weer willen gebruiken.

App instellingen:
![App_Inst_Adres](https://github.com/robertraaijmakers/com.trashchecker/assets/143023971/1cdcfb30-c060-416e-b560-9807ea264a5c)
![App_Inst_Hand](https://github.com/robertraaijmakers/com.trashchecker/assets/143023971/d0844c7c-865e-4030-9081-b64757809c04)

Geplande data 
![Data_Afval](https://github.com/robertraaijmakers/com.trashchecker/assets/143023971/6381163d-65f8-4457-ab39-18c6486ee2d8)

Resultaten:

![Test 21-8-2023](https://github.com/robertraaijmakers/com.trashchecker/assets/143023971/954061a2-d2d0-49ef-b673-958c7e7c091f)
![Test 22-8-2023](https://github.com/robertraaijmakers/com.trashchecker/assets/143023971/42ccede9-4a42-42e9-ac3f-80f586217026)
![Test 23-8-2023](https://github.com/robertraaijmakers/com.trashchecker/assets/143023971/32762e9a-7432-41ea-9531-3c57c34b7535)

Rob

**Comment by robertraaijmakers** [comment]
Beste @RobRebel ,

Bedankt voor het bericht en de uitgebreide screenshots. Mag ik vragen waarom je voor een handmatige invoer hebt gekozen?

Als ik het adres invoer dan krijg je (als je helemaal onderaan scrolt in de settings pagina, onder het kopje "debug") de onderstaande ophaaldata te zien:
`{
  "PMD": [
    "2023-01-05",
    "2023-01-19",
    "2023-02-02",
    "2023-02-16",
    "2023-03-02",
    "2023-03-16",
    "2023-03-30",
    "2023-04-13",
    "2023-04-28",
    "2023-05-11",
    "2023-05-25",
    "2023-06-08",
    "2023-06-22",
    "2023-07-06",
    "2023-07-20",
    "2023-08-03",
    "2023-08-17",
    "2023-08-31",
    "2023-09-14",
    "2023-09-28",
    "2023-10-12",
    "2023-10-26",
    "2023-11-09",
    "2023-11-23",
    "2023-12-07",
    "2023-12-21"
  ],
  "GFT": [
    "2023-01-12",
    "2023-01-26",
    "2023-02-09",
    "2023-02-23",
    "2023-03-09",
    "2023-03-23",
    "2023-04-06",
    "2023-04-20",
    "2023-05-04",
    "2023-05-19",
    "2023-06-01",
    "2023-06-15",
    "2023-06-29",
    "2023-07-13",
    "2023-07-27",
    "2023-08-10",
    "2023-08-24",
    "2023-09-07",
    "2023-09-21",
    "2023-10-05",
    "2023-10-19",
    "2023-11-02",
    "2023-11-16",
    "2023-11-30",
    "2023-12-14",
    "2023-12-28"
  ],
  "PAPIER": [
    "2023-01-28",
    "2023-02-25",
    "2023-03-25",
    "2023-04-22",
    "2023-05-27",
    "2023-06-24",
    "2023-07-22",
    "2023-08-26",
    "2023-09-23",
    "2023-10-28",
    "2023-11-25",
    "2023-12-23"
  ]
}`

Hier staan o.a. de data in die ook op het screenshot van afvalwijzer te zien zijn. Dit zijn dus de juiste data.

Als je met de huidige settings (de handmatige invoer) naar onderen scrolt zal te zien zijn dat het ook werkt zoals het nu geconfigureerd is. Daar zal in de lijst namelijk voor GFT, op basis van de ingevoerde handmatige data, de volgende ophaaldata gevuld worden: 7 augustus en 21 augustus (namelijk in de week van 10 augustus, elke maandag om de week, dus dat is 7 augustus en 21 augustus). Dit komt ook overeen met uw eigen testresultaten uit de screenshots.

Mijn advies is om alle instellingen in te stellen op "Based on API", vervolgens het adres aan te passen om de laatste data op te halen. Dan naar beneden te scrollen en dan zal je in de debug zien dat die hetzelfde resultaat geeft als de lijst hierboven. Vervolgens kan je [als volgt](https://robertraaijmakers.github.io/com.trashchecker/flow-examples.html) een flow instellen om de juiste gegevens naar boven te krijgen en mooie reminders te krijgen. 

<img width="466" alt="image" src="https://github.com/robertraaijmakers/com.trashchecker/assets/1773099/2ebf14bb-44b7-4209-b5cb-1885175686fc">

Succes! :)

Met vriendelijke groet,
Robert Raaijmakers
