### ISSUE TITLE
Logic tags in Advanced flow are not working (v3.2.8 @ HP23)

### ISSUE THREAD

**Issue by stofferr** [robertraaijmakers/com.trashchecker#177]
Hi Robert,

With a classic flow, I can see proper content in the logic tags for trash collected today, tomorrow and day after tomorrow.
With an advanced flow, these tags only seem to be producing "NIETS" as content (but yes, on the expected dates).

This is the flow:
![image](https://github.com/robertraaijmakers/com.trashchecker/assets/40294915/b4dd650b-ca87-4217-a4eb-092a9a107b5f)

The result:
![image](https://github.com/robertraaijmakers/com.trashchecker/assets/40294915/d3f263c3-91c5-403f-961d-42a0b56a2a76)

The JSON:
![image](https://github.com/robertraaijmakers/com.trashchecker/assets/40294915/629480fe-60a6-4c07-871b-997ca55959fb)

The date: 2023-09-21

The expected result would be: “REST”, but as you can see it shows “NIETS/NOTHING”

These are my configs: 
![image](https://github.com/robertraaijmakers/com.trashchecker/assets/40294915/9a0081f8-ac0a-4f17-871c-51e96bbe72b9)
![image](https://github.com/robertraaijmakers/com.trashchecker/assets/40294915/2cbe0113-f86f-4d9b-9872-6b336bb9c206)

It is using the exact string I have configured for Nothing: “NIETS”. Which is the literal text I configured. But I don’t think the app should have triggered this text.

In my logs I can see that on the date of the REST trash, the log is written, however, the tags “collected today/tomorrow/day-after-tomorrow” consistently hold the text NIETS. I have had this 2x already; one time for PMD, and now for REST.

So it seems that it finds a matching entry in the JSON on the correct dates, but the mapping to the text fo rthe logic tags in Advanced Flow only, seems incorrect. I suspect a bug but cannot be sure. Open to suggestions…

**Comment by stofferr** [comment]
Hi @robertraaijmakers,
Ik heb hem nu handmatig getest en dat lijkt te werken.
Ik heb de starttijd nu naar 1:01 omgezet. Kijken wat er gebeurt vannacht...

**Comment by stofferr** [comment]
Hoi Robert, om 1:01u werkt het prima.
Kan inderdaad een locale probleem zijn...

⁣Get BlueMail for Android ​

**Comment by robertraaijmakers** [comment]
Top, bedankt voor de terugkoppeling, ik zal eens kijken of ik wat kan vinden om dit nog extra te omzeilen en zal deze dus even open laten staan.

**Comment by robertraaijmakers** [comment]
There seems no good way to retrieve the right timezone (so correction for Daylight saving time etc.) for Homey. So I can't fix this issue. Best is to just run the flows around 2 or 3 midnight. Then you are always safe.
