### ISSUE TITLE
Recycle API - Restafval vs Grofvuil

### ISSUE THREAD

**Issue by Phunkay** [robertraaijmakers/com.trashchecker#178]
Hoi,

App werkt top, alleen wordt zowel restafval als grofvuil als grofvuil aangegeven.

Ook zou ik de standaard tekst willen kunnen aanpassen. Doordat Homey in Engels staat zijn de spraakteksten van de app automatisch Engels. Ik heb nu een flow gemaakt waarmee ik teksten genereer op basis van de ophaling.

Alvast bedankt om dit eventueel te bekijken! :)

>  @`
![1000010632](https://github.com/robertraaijmakers/com.trashchecker/assets/22442908/b2572cc7-872d-4591-93d0-b7bbeabfa054)
![1000010631](https://github.com/robertraaijmakers/com.trashchecker/assets/22442908/1a80156c-445c-47ba-9489-67b727c95015)
![1000010633](https://github.com/robertraaijmakers/com.trashchecker/assets/22442908/04695c48-6900-4491-9b2f-03c710e7c7a8)
`

**Comment by robertraaijmakers** [comment]
Hoi,

Fijn om te horen dat de app fijn werkt. Onder settings kan je zelf de labels aanpassen naar het NL of Simlish, wat je zelf wilt. Meer daarover vind je in de documentatie hier: https://robertraaijmakers.github.io/com.trashchecker/settings.html

Wat betreft grofvuil en restafval, dit hangt heel erg af van wat voor onderscheid er gemaakt wordt in de API die je gebruikt. Heb je een voorbeeld postcode + huisnummer en een dag waarop grofvuil opgehaald zou worden en een dag waarop restafval opgehaald wordt?

**Comment by Phunkay** [comment]
Oh shit, geen notificatie gekregen daarom je reactie gemist, excuses. 
Ik gebruik volgend adres: De Pelgrim 24, 2650 Edegem
Als ik alles volgens API laat lopen, staat er alleen GROF in de debug json, met de data van Restafval. (Zie schermafdruk)
![Screenshot_20241002-182027](https://github.com/user-attachments/assets/18369ac8-b897-4e2e-8070-9e98c217e1d3)

Als ik restafval dan uitzet (N/A) staat in de json GROF met een restafval datum en REST zonder datum.
Als ik grof uitzet (N/A) dan staat in de json GROF zonder datum en staat er geen REST.

Lijkt dus alsof de Recycle app rest en grof afval onduidelijk rapporteert.
Ik zal proberen hier regelmatig te kijken in geval je antwoord. Waarvoor alvast dank!

**Comment by robertraaijmakers** [comment]
Hi @Phunkay ,

Beetje lang geleden deze thread. Maar als ik kijk naar je originele vraag dan vroeg je je af hoe je de teksten kon aanpassen. Zoals je mogelijk op je screenshot hebt kunnen zien is de settings pagina de plek om dat te doen.

Door "__time__ __type__ is collected." aan te passen naar "__time__ wordt __type__ opgehaald."
en door "__time__ __types__ are collected." aan te passen naar "__time__ worden __types__ opgehaald."

En vervolgens per trash type even de NL naam in te vullen krijg je al je teksten netjes in het Nederlands.

Hierin kan je ook je andere probleem oplossen dat in BE iets als GROF wordt geraporteerd terwijl het RESTafval is. Als je zelf je label tekst van grof (dus bij Bulky waste) naar rest aanpast, dan krijg je voortaan gewoon netjes te zien dat restafval opgehaald wordt.

Hopelijk heb je hiermee het antwoord wat je zoekt.

**Comment by robertraaijmakers** [comment]
Er wordt op de locatie geen grof afval opgehaald. Althans, die data komt niet terug in de Recycle app... Dus die kan dan ook niet weergegeven worden.

Mocht die data daar wel in staan dan ontvang ik graag een screenshot van hoe die dan in hun app getoond wordt. Dan kan ik ook kijken of ik die ergens vandaan kan halen.

**Comment by Phunkay** [comment]
Hier zie je de ophalingen van de komende maand. Met op 18 oktober een grofvuil (bulky waste, telefoon staat op Engels).
![Screenshot_20241003-225802](https://github.com/user-attachments/assets/bdd0f2b6-a3bb-44ed-bbb8-64a86ec734f3)
Ter vergelijking, de debug info in Trashcan Reminder, waar [Grof] de data van Restafval (grijs in de Recycle app op 7 en 21 oktober) toont en er geen [Rest] category staat. Wanneer ik Restafval uitzet (N/A) staat de category in de debug info maar nog steeds zonder data.
![Screenshot_20241003-230216](https://github.com/user-attachments/assets/3537ccb4-a88b-41da-951d-9f9967507315)
Hoopt dat dit iets helpt...

**Comment by robertraaijmakers** [comment]
I found the issue, still weird that it wasn't showing before. But a fix is available here: https://homey.app/a/com.trashchecker/test/

**Comment by Phunkay** [comment]
Sorry voor het heropenen maar sinds de heropbouw van de app lijkt bovenstaand probleem teruggekeerd.
Data voor restafval worden bij grofvuil ingedeeld en aangegeven. Lijkt hetzelfde probleem als voordien.

**Comment by robertraaijmakers** [comment]
Sorry @Phunkay, fixed it again :)

**Comment by Phunkay** [comment]
> Sorry [@Phunkay](https://github.com/Phunkay), fixed it again :)

You the best!!! 😁
