### ISSUE TITLE
Using config for Belgian address with Recycl app not working

### ISSUE THREAD

**Issue by ericfran** [robertraaijmakers/com.trashchecker#179]
Hi
I try to configure th3 application for a Belgian address using the Recycl app but received the message address not supported. When I go to the recycle page : https://www.recycleapp.be/dashboard my adress exist and be found. 

Code log: 
bbe7595b-8bc3-4c69-b21f-8dccc7c5012e

Regards

**Comment by robertraaijmakers** [comment]
I have checked the log you submitted and you entered the street with a space behind it. If you remove the space behind the street name it probably works.

**Comment by ericfran** [comment]
Hi,Just try it, remove and check it ny space seems same issueLog id : db2d2730-8970-46dd-a37d-f9cca57e82ccRegardsEricOn 2 Dec 2023, at 13:16, Eric FRANCKX ***@***.***> wrote:﻿Ohhh ok will try againI was trying also again but will try againThanksOn 2 Dec 2023, at 13:12, Robert ***@***.***> wrote:﻿
I have checked the log you submitted and you entered the street with a space behind it. If you remove the space behind the street name it probably works.

**Comment by ericfran** [comment]
HiStill not workRegardsEricSent from my iPhoneOn 2 Dec 2023, at 13:18, Eric FRANCKX ***@***.***> wrote:﻿Hi,Just try it, remove and check it ny space seems same issueLog id : db2d2730-8970-46dd-a37d-f9cca57e82ccRegardsEricOn 2 Dec 2023, at 13:16, Eric FRANCKX ***@***.***> wrote:﻿Ohhh ok will try againI was trying also again but will try againThanksOn 2 Dec 2023, at 13:12, Robert ***@***.***> wrote:﻿
I have checked the log you submitted and you entered the street with a space behind it. If you remove the space behind the street name it probably works.

**Comment by ericfran** [comment]
Hi,New report generated. ID : b5ce5212-05df-45e1-999e-74805f9e4495RegardsEricOn 4 Dec 2023, at 19:07, Eric FRANCKX ***@***.***> wrote:﻿HiStill not workRegardsEricSent from my iPhoneOn 2 Dec 2023, at 13:18, Eric FRANCKX ***@***.***> wrote:﻿Hi,Just try it, remove and check it ny space seems same issueLog id : db2d2730-8970-46dd-a37d-f9cca57e82ccRegardsEricOn 2 Dec 2023, at 13:16, Eric FRANCKX ***@***.***> wrote:﻿Ohhh ok will try againI was trying also again but will try againThanksOn 2 Dec 2023, at 13:12, Robert ***@***.***> wrote:﻿
I have checked the log you submitted and you entered the street with a space behind it. If you remove the space behind the street name it probably works.

**Comment by robertraaijmakers** [comment]
@ericfran I have fixed it (I hope :)). You can test it by installing this version https://homey.app/a/com.trashchecker/test/

**Comment by ericfran** [comment]
HiThanks some day ago I saw it working and revive notification I will check if still work in coming daysdank UOn 19 Jan 2024, at 13:11, Robert ***@***.***> wrote:﻿
@ericfran I have fixed it (I hope :)). You can test it by installing this version https://homey.app/a/com.trashchecker/test/

**Comment by robertraaijmakers** [comment]
Great to hear!
