### ISSUE TITLE
Tag language

### ISSUE THREAD

**Issue by PetrichorXyz** [robertraaijmakers/com.trashchecker#18]
![image](https://user-images.githubusercontent.com/2332343/36350472-b2db3794-1498-11e8-8610-f181e50bfb0a.png)

![image](https://user-images.githubusercontent.com/2332343/36350484-d20dadfe-1498-11e8-9675-3e790b0b5224.png)

Issue:
![image](https://user-images.githubusercontent.com/2332343/36350510-2883d794-1499-11e8-9102-fce9d35875c0.png)

Text in tags section is in English. It should be in Dutch. All Homey's language settings are Dutch.

**Comment by robertraaijmakers** [comment]
You can change the text via the settings page of the afval herinnering app.
