### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by StaX91** [robertraaijmakers/com.trashchecker#180]
Hi @robertraaijmakers,

I am not much a developer but have some technical background. I read that you don't follow up on requests to add cities so i though: Let's try it myself. Shoul be able to.

I forked your rep. But it seems it's not the latest version? Looking at homechaneglog.json it goes up to 3.2.3 while the Homey app is already on 3.2.9? 

Hope to hear from you! 

Kind regards

**Comment by robertraaijmakers** [comment]
Hi there, 

It’s still in the beta branch still and not in main:

https://github.com/robertraaijmakers/com.trashchecker/tree/beta

**Comment by StaX91** [comment]
> Hi there,
> 
> It’s still in the beta branch still and not in main:
> 
> https://github.com/robertraaijmakers/com.trashchecker/tree/beta

Thanks! I tried to added Gemeente Meppel to the best of my knowledge (this is new for me). Also added myself as a contributor (vrijwilliger), which would be nice. If you don't agree with that or don't want that, that's fine.
