### ISSUE TITLE
Support for Avri Tiel?

### ISSUE THREAD

**Issue by Gwdijk** [robertraaijmakers/com.trashchecker#183]
Hi there, 

Would it be possible to add support for Avri in Tiel? 
Thanks in advance!

Glenn

**Comment by robertraaijmakers** [comment]
Details:
4002AK, Tiel
[WasteApi Ximmio](https://www.avri.nl/inwoners/afval/afvalkalender/)

**Comment by Gwdijk** [comment]
> Hi, yes that is possible. You can find more information here: [developer guidelines](https://robertraaijmakers.github.io/com.trashchecker/developer-guidelines.html)
> 
> Details: 4002AK, 14 [WasteApi Ximmio](https://www.avri.nl/inwoners/afval/afvalkalender/)

Awesome, will have a look tomorrow, thanks!

**Comment by robertraaijmakers** [comment]
You can test it here: https://homey.app/a/com.trashchecker/test/

**Comment by Gwdijk** [comment]
Thank you so much Robert. Any other way than PayPal to buy you a small beer?
