### ISSUE TITLE
Gemeente Assen is overgestapt (1 jan. 2024) van "Mijn Afvalwijzer" naar eigen app/portal

### ISSUE THREAD

**Issue by KammAndRe** [robertraaijmakers/com.trashchecker#184]
Is het mogelijk om Homey Afval Herinnering 2.0 te updaten met de gegevens van de gemeente Assen?

meer info:
https://www.assen.nl/ophaaldagen-afvalwijzer
https://21burgerportaal.mendixcloud.com/p/assen/landing/

**Comment by robertraaijmakers** [comment]
Hi, dat is zeker mogelijk. Meer informatie vind je hier: [developer guidelines](https://robertraaijmakers.github.io/com.trashchecker/developer-guidelines.html)

Voorbeeldadres Assen (mochten anderen hier wat mee willen doen): 9402 JW, 254

**Comment by robertraaijmakers** [comment]
Support added, you can test it here: https://homey.app/a/com.trashchecker/test/

**Comment by KammAndRe** [comment]
Hi Robert, tested on my Homey Pro 23. The app is working for de gemeente Assen now. thank you
