### ISSUE TITLE
Recycle app (BE) doesn't work anymore in afval herinnering app.

### ISSUE THREAD

**Issue by joris666** [robertraaijmakers/com.trashchecker#186]
The "afval herinnering 2.0"app stops working... reinstall it..but now it's impossible to fill in my home addres.
It says " dit adres wordt niet ondersteund"
When i open the recycle app(be)and fill in my home adress it excits....

**Comment by robertraaijmakers** [comment]
Hi, has it worked before with the same address?
And can you provide a sample address, because other BE addresses are working, so there is probably something special with this address.

**Comment by robertraaijmakers** [comment]
Key had changed, can you verify here: https://homey.app/a/com.trashchecker/test/ ?

**Comment by joris666** [comment]
yess, it worked again with the testversion!!
Thanks Robert for the quick response!!!

**Comment by joris666** [comment]
did i made a mistake somewhere,somehow?

**Comment by robertraaijmakers** [comment]
Nope, they changed their API key (secret) so the app wasn't able to authenticate to their Web API anymore. So I downloaded a new secret from their website.
