### ISSUE TITLE
Mijn afvalwijzer 

### ISSUE THREAD

**Issue by RN88R** [robertraaijmakers/com.trashchecker#187]
When i set up the app on my Homey pro and config my zipcode, “milieudienst” on every Wednesday is not loaded.
(PMD = called Milieudienst in this area.)

When i go to mijn afvalwijzer and enter my zipcode everything looks fine.
(9821 TT, nr 9 bijv.)

Is the API not working correct?
I know you can add dates manually but for a whole year and without coding skills my first step is just asking.

kind regards 
Ron

**Comment by robertraaijmakers** [comment]
Is the PMD collected every week? That is quite often, or does "milieubus" / "Milieudienst" also collect other stuff?
I'm more tempted to put the milieudienst below "glas" to keep it clean for other places that do both the milieudienst and seperate PMD containers.

**Comment by RN88R** [comment]
Milieudienst collect plastic/paper/glass every week on Wednesdays.
People dont have containers for milieudienst, they just drop bags/boxen a side the road every week.

in this area we have 2 containers. Grey and green.
(Restafval and GFT) every other week.

below glass is fine by me 😃👍

**Comment by robertraaijmakers** [comment]
I have put it in the category "glass" for now, can you check if you see your dates now with this version: https://homey.app/a/com.trashchecker/test/ ?

**Comment by RN88R** [comment]
Yes!! It’s working under the name glass!
Based on API, all Wednesdays for 2024 are loaded.
Thank you very much 🙏
