### ISSUE TITLE
triggercard is false even if postalcode is green in settings and current day is pickup day

### ISSUE THREAD

**Issue by eelco2k** [robertraaijmakers/com.trashchecker#19]
Today the paper should be collected. I have a setup a simple Flow: but when i test it on the 19-02-2018. it gives me a red X. which means it's not true. Is the date format of the RD4 Api wrong?

![schermafbeelding 2018-02-19 om 09 13 48](https://user-images.githubusercontent.com/878103/36367942-4255db06-1555-11e8-8a6a-dabe51aba35c.png)

![schermafbeelding 2018-02-19 om 09 09 07](https://user-images.githubusercontent.com/878103/36367895-0bd39a82-1555-11e8-8c10-a51b4a55b88a.png)

![schermafbeelding 2018-02-19 om 09 09 52](https://user-images.githubusercontent.com/878103/36367896-0bea00e2-1555-11e8-985c-de88bc9ee584.png)

**Comment by robertraaijmakers** [comment]
Very strange behavior this. I will have a look soon.

**Comment by eelco2k** [comment]
Thnx!

**Comment by wdlh** [comment]
@robertraaijmakers ,
i have the same problem since this morning. but the i use the "afvalwijzer" data.
i hope you can fix this because i need this reminder! ;-)

**Comment by robertraaijmakers** [comment]
Haven't had time to test the change yet. But changed the refresh to 5 O'clock. Also added extra debug information to the settings page so that everyone can see what collection days are stored in Homey. New version (beta, 2.4.1) will be available for testing when Athom approves the changes. Will have to wait till saturday to see if it works :)

**Comment by eelco2k** [comment]
Hi @robertraaijmakers,

I have found the issue:

the function did not parse the body result
```
function afvalkalenderRD4(postcode, housenumber, country, callback)
{
	console.log("Checking afvalkalender RD4");

	var url = `https://rd4.syzygy.eu/${postcode}/${housenumber}/`;

    request(url, function (err, res, body) {
        if (!err && res.statusCode == 200) {
        	var result = JSON.parse(res.body);
	       	console.log(result);
            return callback(null, result);
        } else {
            return callback(new Error('Invalid location'));
        }
    });
}
```

the function of the RD4 should be replaced with this one above.. i'v tested it and it should work.
