### ISSUE TITLE
Rova 

### ISSUE THREAD

**Issue by robindelange** [robertraaijmakers/com.trashchecker#190]
Bye Robert, 

I noticed that via homey I no longer got a notification even though GFT should be collected. when checking, the date is also correct in the settings of the app however when saving the Waste calendar ROVA Source, it gives the message: this address is not supported.

When checking in the rova app they say they have a new app: My Rova. could it be that this needs to be adjusted? i have tried everything but i don't get any notifications anymore. 

I had a look at your site, but I'm not a developer so I can't add it myself.

Thanks in advance for your answer and time!

Robin de Lange

**Comment by Seinuh** [comment]
Same here, Rova down

**Comment by yustmenl** [comment]
I have the same issue with Afvalstoffendienst (Den Bosch) at least the error, to my knowledge there is no new app for them

**Comment by robertraaijmakers** [comment]
ROVA seems to indeed be down. Den Bosch is working fine in the test cases.

**Comment by robertraaijmakers** [comment]
Rova should be working again on this release: https://homey.app/a/com.trashchecker/test/

**Comment by goudhaan** [comment]
Yes sir it does. Thanks so much

**Comment by Seinuh** [comment]
Confirmed 😊

**Comment by robindelange** [comment]
Nice,  thanks robert!
