### ISSUE TITLE
App werkt sinds kort niet meer

### ISSUE THREAD

**Issue by yustmenl** [robertraaijmakers/com.trashchecker#191]
Het lijkt erop dat de app sinds kort niet meer werkt voor de gemeente den bosch
ik krijg de volgende melding als ik het adres opnieuw invoer omdat ik geen meldingen meer kreeg.

"DIt adres wordt niet ondersteund"

Zou je hier naar kunnen kijken?

3abc836a-7af8-4344-a4c6-3eacd6286ba7

Is het diagnostisch rapport van homey voor als je het nodig hebt

alvast bedankt!

**Comment by robertraaijmakers** [comment]
Heb je een voorbeeld postcode & huisnummer voor me? Die van mijn unit test gaat gewoon goed (5231PB, 4) :)


Checking general afvalkalenders API implementation URL: denbosch.afvalstoffendienstkalender.nl
{
  REST: [
    '2024-01-04', '2024-01-18',
    '2024-01-25', '2024-02-01',
    '2024-02-05', '2024-02-26',
    '2024-03-18', '2024-04-08',
    '2024-04-29', '2024-05-18',
    '2024-06-10', '2024-07-01',
    '2024-07-22', '2024-08-12',
    '2024-09-02', '2024-09-23',
    '2024-10-14', '2024-11-04',
    '2024-11-25', '2024-12-16'
  ],
  PAPIER: [
    '2024-01-06', '2024-01-29',
    '2024-02-20', '2024-03-19',
    '2024-04-16', '2024-05-14',
    '2024-06-11', '2024-07-09',
    '2024-08-06', '2024-09-03',
    '2024-10-01', '2024-10-29',
    '2024-11-26', '2024-12-24'
  ],
  GFT: [
    '2024-01-11', '2024-02-07',
    '2024-02-21', '2024-03-06',
    '2024-03-20', '2024-04-03',
    '2024-04-17', '2024-05-01',
    '2024-05-15', '2024-05-29',
    '2024-06-12', '2024-06-26',
    '2024-07-10', '2024-07-24',
    '2024-08-07', '2024-08-21',
    '2024-09-04', '2024-09-18',
    '2024-10-02', '2024-10-16',
    '2024-10-30', '2024-11-13',
    '2024-11-27', '2024-12-11',
    '2024-12-21'
  ],
  KERSTBOOM: [ '2024-01-11' ],
  PMD: [
    '2024-02-12', '2024-03-04',
    '2024-03-25', '2024-04-15',
    '2024-05-06', '2024-05-27',
    '2024-06-17', '2024-07-08',
    '2024-07-29', '2024-08-19',
    '2024-09-09', '2024-09-30',
    '2024-10-21', '2024-11-11',
    '2024-12-02', '2024-12-23'
  ]
}
