### ISSUE TITLE
Feature request: Possibility to be picked up both tomorrow as well as today.

### ISSUE THREAD

**Issue by ezwep** [robertraaijmakers/com.trashchecker#193]
Until now, I always used the tag "picked up tomorrow" and in the flow I would neatly receive a message, which was also sent through my Sonos speakers. This notification would be given at 6 PM in the evening. However, it is sometimes forgotten, so I have set up a notification for the day the container is picked up as well. But the notification still says it will be picked up tomorrow, not today. I could of course set up the flows per container and per moment, but it would be nice if when I choose for today's pickup in the flow, the notification would also reflect this.

**Comment by robertraaijmakers** [comment]
If you use the tag “picked up today” instead of “picked up tomorrow” then you get the right notification.

See also: https://robertraaijmakers.github.io/com.trashchecker/flow-examples.html

![image](https://github.com/robertraaijmakers/com.trashchecker/assets/1773099/65b9302d-a097-40f4-9c84-2a46eeebd428)

**Comment by ezwep** [comment]
I just tested it again. I received the message that the container will be picked up tomorrow. I suspect this is because the global setting is set to "picked up tomorrow". Yesterday evening at 6:00 PM I did receive the correct message.

<img width="215" alt="image" src="https://github.com/robertraaijmakers/com.trashchecker/assets/42382514/37634f79-fe6f-4e20-ae3d-d2999c8fd8b6">

**Comment by robertraaijmakers** [comment]
If you use the tag “picked up today” instead of “picked up tomorrow” then you get the right notification.

See also: https://robertraaijmakers.github.io/com.trashchecker/flow-examples.html
