### ISSUE TITLE
Missing owner name

### ISSUE THREAD

**Issue by Thull3** [robertraaijmakers/com.trashchecker#195]
The flow isn't working and says missing owner name in the flow.
If I add a new it says the correct name in the beginning until I save the flow and go back and later into the flow again?

![image](https://github.com/robertraaijmakers/com.trashchecker/assets/47575085/5a4be0cb-345b-4244-8bea-aca515e0031d)

**Comment by robertraaijmakers** [comment]
Hi @Thull3,

Thanks, what is exactly the issue except that Homey doesn't show the app name?

**Comment by Thull3** [comment]
It have stopped running since last time it runned the flow without any changes to the flow. But maybe some other issue and not yours. But only thing I recognize what the name error but maybe have been there before ?

**Comment by robertraaijmakers** [comment]
So the flow stops running?
Do you know if the app stops running to? And if so, can you send me a manual log file?

I haven’t seen this behaviour before, but it might be due to the different localisation.

**Comment by robertraaijmakers** [comment]
Closed due to inactivity.
