### ISSUE TITLE
Afvalkalender Cyclus not working any more

### ISSUE THREAD

**Issue by JustindeKnegt** [robertraaijmakers/com.trashchecker#196]
Since a few weeks it seems that the app won't connect to the Afvalkalender Cyclus in Gouda any more.
The app worked for a long time for me, but now it does not recognize my address (postal code + nr) or the api methode to refresh the data.
I saw the correct dates in the debug information (PMD 2024-07-04), but the card in the flow keeps giving "no" as a result if for example the PMD should be collected today (it gave me YES when I reverted the card if PMD was not to be collected today)

To be sure it was not a glitch I have reinstalled the app, but I still get the same error message (The address is not supported) with both the postal code and API option.

I really hope you can investigate this issue, we really like this app and we would love to keep using it!

Thank you for your help in advance.

ps If you need more information please  let me know.

**Comment by Ralphjes** [comment]
I'm having the same problem! My address isn't recognized anymore.

**Comment by robertraaijmakers** [comment]
Can you please check the latest version? Cyclus updated their API again and I had to do some fixes.

**Comment by Ralphjes** [comment]
It's updated to 3.2.16. When I try to verify my address it keeps haning on 'adres checken...'

![image](https://github.com/robertraaijmakers/com.trashchecker/assets/175051834/66664466-6d06-4c80-8ccd-3c77fec32fa8)

**Comment by JustindeKnegt** [comment]
I have also updatet the app to version 3.2.16, but I got the same  "adres checken..." message as Ralphjes for both options (postal code and API).

**Comment by robertraaijmakers** [comment]
Strange, if I try with another zip it works fine. What is the zip that you try with?

![IMG_6814](https://github.com/robertraaijmakers/com.trashchecker/assets/1773099/bcce3921-2911-4ab6-a329-0aa27b135f28)

**Comment by JustindeKnegt** [comment]
Just to be sure I checked with the same postal code as in your image, but even with that one I get "adres checken.."

![AfvalHerinnering_cyclus_adreschecken](https://github.com/robertraaijmakers/com.trashchecker/assets/174731142/736e72fa-3014-4b18-9fed-6034abac3caf)

The postal code I use is 2804 GV, 34

**Comment by JustindeKnegt** [comment]
I saw in the image that you are using English as system language, where I use Dutch. Therefor I switched to English as well, but that did not solve the problem. Just to let you know :)

**Comment by JustindeKnegt** [comment]
OK, I think I got it solved!

I performed some tests with the System languages (English, Dutch), but also performed a reinstall of the application with the different languages.
The system language did not matter, however the reinstallation of the application did!
It is still  version 3.2.16, but now it is working. I get the "address updated to..." message and I see the dates in the debug information.
So for some reason it seems that updating to this version did something else than the reinstall.

To be sure that everything is working I will test my flow tomorrow, that is when I should get a notification, and I will provide an update with the result.

I hope a reinstallation of the app solves the problem for Ralphjes as well.

@robertraaijmakers : thank you for your help and quick support!

**Comment by Ralphjes** [comment]
Unfortunatelly it's not solved for me. I removed an reinstalled the app, restarted my Homey, but still no zipcodes succeed. I'm still on the 'adres checken...'.

**Comment by JustindeKnegt** [comment]
Not sure if it matters (or if it is different from how you performed the deinstallation and installation) but I deinstalled the app, waited a few minutes, rebooted Homey and after that I installed the application again.

After that it was working for me with both the postal code as provided in the images as with my own postal code

**Comment by robertraaijmakers** [comment]
You have to uninstall the app and then reboot Homey. Only then it empties its cache from the app. Probably there is something wrong in there and this is the only way to fix it for now.

**Comment by Ralphjes** [comment]
Thanks for you help. I really appreciate it. I tried the steps (uninstall, wait, reboot, install) but still it keeps hanging on 'adres checken...'. But I dit found something... I have Homey Pro 2023. That's the one it keeps failing on. But I also have an Homey Pro 2016-2019. On that one there are no issues. It finds my address right away.

**Comment by Ralphjes** [comment]
For now I removed the app. I hope it will be fixed sometime.

**Comment by JustindeKnegt** [comment]
Klopt, bij mij werkt het nu weer als vanouds op mijn HP 2023.
