### ISSUE TITLE
My afval-service seems to have moved elsewhere. Possibly all of "Westelijke Mijnstreek"

### ISSUE THREAD

**Issue by PhilippeMH** [robertraaijmakers/com.trashchecker#197]
Hi Robert,

It looks like the trash service in my town (Stein) made some changes. We now seem to work with [RWM](https://rwm.nl/). Since this represents the "Westelijke Mijnstreek" it could be Homey users in the following municipals are also affected: [Beek](https://nl.wikipedia.org/wiki/Beek_(gemeente)), [Sittard-Geleen](https://nl.wikipedia.org/wiki/Geleen), [Schinnen](https://nl.wikipedia.org/wiki/Schinnen_(gemeente)) en [Stein](https://nl.wikipedia.org/wiki/Stein_(gemeente)).

My zip code address used to work with the "MijnAfvalwijzer" API, but it can no longer be found there. My "and" cards do no longer give the correct results on thrash days, even though there seems to be some residual information in the app settings.
![image](https://github.com/user-attachments/assets/9ee105fb-e9af-4f78-a597-67ff2d9eaf66)
![image](https://github.com/user-attachments/assets/67b64588-0dbe-4eee-8c1b-e2182781d9f7)

I presume this is caused by the change in trash services or their organization. Or, maybe you can check if it is something else. Anyway, I thought you needed to know. Can you let me know if you see a solution (on the horizon)?

Groetjes,
Philippe

**Comment by RogerGorissen** [comment]
Any news or developments yet?
I live in Sittard and also noticed that the app doesn't work anymore. Checking whether "iets" will be collected tomorrow (or even the day after tomorrow) results in an exclamation mark. Although the dates in the debug info are correct, so the API seems to work. Or are they perhaps written in a different format as before?

**Comment by PhilippeMH** [comment]
I called RWM and trey tell me they no longer support the avfalwijzer API. They only provide data via their own app, and do not plan to publicize any API's for that, due to "privacy reasons". There do not need to by "any" true privacy-sensative datums in the afval API return info- only coming from the users side, postal code and house number. This all sounds really starnge to me.

If you are from around the sittard geleen area **PLEASE COMPLAIN WITH RWM**
https://rwm.nl/contact

**Comment by RogerGorissen** [comment]
Philippe,

Strange action from RWM. I think privacy is not a really valid reason to not using an API or making the dates available.

I've sent an email describing the problem I was facing with their new app. The answer is as follows:

--------

Hartelijk dank voor uw bericht en voor het onder de aandacht brengen van uw zorgen omtrent de integratie van onze nieuwe afvalapp met domoticasystemen.
 
U heeft gelijk dat we vóór de introductie van onze nieuwe app gebruik maakten van mijnafvalwijzer.nl. Deze website had een koppeling naar de oude API, die door diverse afvalinzamelaars werd gebruikt, waaronder RWM. Helaas is het zo dat de nieuwe website en de ontwikkelaar ervan deze koppeling niet meer bevatten. Wij begrijpen dat dit problemen veroorzaakt voor gebruikers die hun afvalophaalschema's in domoticasystemen integreren.
 
Het is belangrijk op te merken dat mijnafvalwijzer.nl geen door ons beheerde applicatie is, waardoor we geen directe controle hebben over de functionaliteit daarvan. Daarnaast kunnen wij, als RWM, geen gegevens verstrekken van de API's van onze applicaties vanwege de privacy en beveiliging van de overige gegevens die hierin ook verwerkt worden.
 
Een mogelijke oplossing voor uw situatie zou kunnen zijn om het kalenderbestand van de afvalwijzer uit de RWM-app te downloaden. Dit bestand kunt u vervolgens toevoegen aan uw persoonlijke agenda. Indien deze agenda is opgenomen in uw domoticasysteem, zou dit als een workaround kunnen dienen om de afvalophaaldagen alsnog te integreren.
 
We hopen dat deze workaround u kan helpen, en we werken continu aan verbeteringen om onze dienstverlening verder te optimaliseren.

-----

Maybe it's an option to generate the calendar file and extract the dates from it. But that's only something @robertraaijmakers can do.

**Comment by PhilippeMH** [comment]
> Daarnaast kunnen wij, als RWM, geen gegevens verstrekken van de API's van onze applicaties vanwege de privacy en beveiliging van de overige gegevens die hierin ook verwerkt worden.

Dat hangt volledig van je API implementatie af. Onder normale omstandigheden in een architectuur die data beschermt hoeft dit zeker niet het geval te zijn. API's publiceren is ook niet alleen een kwestie van je interne API's publiek toegankelijk maken. Ik vindt dit echt5 een poging om de gebruiker zand in de ogen te strooien met jargon. Verkeerde publiek daarvoor denk ik :-)

**Comment by RogerGorissen** [comment]
Dan rest ons niets anders dan RWM te helpen en het data argument te ontkrachten. Het handigst is het publiekelijk bekende mailadres kcc@rwm.nl

**Comment by robertraaijmakers** [comment]
Deze partijen hebben geen idee wat ze wel en niet beschikbaar hebben en geven altijd de AVG/GDPR als argument om geen data beschikbaar te hebben. Was ook toen RMN overging op een nieuwe partij, toen kwam ook dit als argument. Gelukkig lijken ze overgestapt te zijn op een generieke partij, en die heeft gewoon een API beschikbaar. Ik zal kijken of ik die een dezer dagen toe kan voegen aan de app.

Voor mijn eigen referentie, random testadres: 6191CE nr 20 / 26 / 32.

**Comment by RogerGorissen** [comment]
Zou mooi zijn als het lukt! Je denkt dus dat ze over zijn gestapt naar een generieke partij die een publiek toegankelijke API heeft die je kunt gebruiken cq die je al gebruikt?

**Comment by PhilippeMH** [comment]
Ohh dit is goed nieuws, ik zag al een heel traject voor me...

**Comment by robertraaijmakers** [comment]
Het lijkt gelukt, jullie kunnen de nieuwe versie hier testen: https://homey.app/a/com.trashchecker/test/

**Comment by RogerGorissen** [comment]
Postcode en huisnummer worden geaccepteerd, Afvalkalender RWM wordt als bron geselecteerd. Kom al verder dan vorige keer.

Opslaan.

Als ik de flow test of morgen iets worst opgehaald, verschijnt het uitroepteken. Morgen wordt papier opgehaald, dus ik verwacht iets. 

App opnieuw gestart. Bij de debug info staan _geen_ data! Ergens zit nog een foutje.

**Comment by PhilippeMH** [comment]
Mijn volgende is de 124de, dan weet ik of het werkt. Dank je, @robertraaijmakers , ik vind het erg fijn dat ik mijn voice notificaties weer zal kunnen gebruiken!

**Comment by robertraaijmakers** [comment]
> Postcode en huisnummer worden geaccepteerd, Afvalkalender RWM wordt als bron geselecteerd. Kom al verder dan vorige keer.
> 
> Opslaan.
> 
> Als ik de flow test of morgen iets wordt opgehaald, verschijnt het uitroepteken. Morgen wordt papier opgehaald, dus ik verwacht iets.
> 
> App opnieuw gestart. Bij de debug info staan _geen_ data! Ergens zit nog een foutje.

Dat is wel gek. Bij mij werkt het met de test postcode die ik eerder noemde gewoon. Kan je die eens proberen en kijken of er dan wel data in je debug komt te staan? Bij mij levert die postcode het volgende resultaat op.

<img width="207" alt="image" src="https://github.com/user-attachments/assets/73076c21-0cae-4468-b084-04dd90453aaf">

**Comment by RogerGorissen** [comment]
Ook met jouw combinatie PC en huisnr. kreeg ik geen data te zien. 
App verwijderd en testversie opnieuw geïnstalleerd. Met mijn eigen PC en huisnr. kreeg ik nu wél de data voor de redt van het jaar te zien!
Tekst bij de globale tag instellingen aangepast, testflows gedraaid en ik krijg verwachte waardes binnen.

App werkt bij mij nu ook.

Goed gedaan. En dank voor de snelle aanpassingen. Gelukkig wist je wat je moest doen, ondanks het op het eerste moment weinig hoopvolle bericht van RWM.

**Comment by PhilippeMH** [comment]
Ik ben nieuwsgierig, ze stoppen support voor de ene dienst, vertellen me dat er niets mogelijk is, maar ondertussen werken ze met een andere dienst die wel een toegankelijke API heeft?

Het werkt zo te zien bij mij nu ook. Alleen effe de flow testen volgende week.
![image](https://github.com/user-attachments/assets/4a53886e-6885-474a-9bc5-c018e38920d9)

**Comment by robertraaijmakers** [comment]
Goed om te horen dat het weer werkt!

Wat betreft de afvalmarkt. Iedere gemeente is zelf verantwoordelijk om te zorgen dat dit opgehaald wordt, sommige gemeentes slaan de handen ineen met buurtgemeentes om zo een grotere aanbesteding te doen. Daarnaast zijn er een aantal software bedrijven die slim inspelen op deze markt en een standaard pakket aanbieden waarbij bewoners een app en toegankelijke website hebben waarop de bewoners de data in kunnen zien. Gemeentes hebben geen verstand of die partijen wel of geen API aanbieden.

Die partijen willen, om belasting op hun servers te verkleinen, ook niet dat iedereen zomaar de data uitleest. Maar met een beetje reverse engineering zijn van een aantal van de grote aanbieders dus manieren gevonden om de data uit te lezen. Zolang ze dat niet dicht zetten is dat mooi meegenomen en blijft dit werken. Maar is allemaal niet officieel gedocumenteerd en daarom valt er ook nog wel eens wat om en soms is het dan helemaal niet meer mogelijk om het uit te lezen. In dit geval hebben jullie geluk dat ze overgestapt zijn naar een grote partij waarbij dat (nog) wel kan :)

Fijn weekend!

**Comment by PhilippeMH** [comment]
Dank voor de uitleg, ik snappem!

**Comment by PhilippeMH** [comment]
Laatste update: het werkt. Ik werd net gewaarschuwd dat overmorgen de groene ton wordt opgehaald. Fantastisch. Nogmaals mijn dank!!!!
