### ISSUE TITLE
missing waste fraction 

### ISSUE THREAD

**Issue by helmuteke** [robertraaijmakers/com.trashchecker#199]
Hello , 

I'm from Belgium , when i use Recyleapp i get from the app the next waste fraction's

Rest , Grof , PMD , Papier

When i use a add-on in Home assistant i get this from  Available waste types: 

GF(t), Grofvuil, Papier, PMD, Restafval, Wijkinzameling groen

Can you integrate this fraction also in your app please ?

**Comment by robertraaijmakers** [comment]
Do you have an example postal code + number that has these details that you mention?

**Comment by robertraaijmakers** [comment]
Thanks. GF(T) is now added under the GFT fraction.
The 'wijkinzameling groen' is added under Textiel. So you can customize that message under settings to reflect the type that is collected there. The app is not dynamically build, so there are no flexible tags so I 're-use' the unused Textiel tag.

**Comment by helmuteke** [comment]
alright ,

when do i see changes ?
