### ISSUE TITLE
Ondersteuning Afval3xbeter App

### ISSUE THREAD

**Issue by Dinky2534** [robertraaijmakers/com.trashchecker#201]
Hallo Robert,

Kwam tot de ontdekking dat de afvalkalender Etten-Leur (NL) momenteel niet meer werkt. Bij de debug info in de app zie ik dat de laatst opgehaalde datum 01 augustus is. Als ik bij "Trashcan Reminder Settings" op opslaan druk krijg ik ook een foutmelding dat het adres niet wordt ondersteund (heeft na je aanpassingen in februari 2023 probleemloos gewerkt). 

Als ik op https://www.mijnafvalwijzer.nl/ mijn adres invoer wordt het adres wel gevonden.

Heb je hier een oplossing voor?

Vriendelijke groet,

Harno

_Originally posted by @Dinky2534 in https://github.com/robertraaijmakers/com.trashchecker/issues/161#issuecomment-2395518301_

**Comment by robertraaijmakers** [comment]
Thanks, they seem to have updated their API again... added a fix for you, will be published with next release and currently already available in the beta channel. https://homey.app/a/com.trashchecker/test/

**Comment by Dinky2534** [comment]
Thanks for the quick fix Robert, great! It works again. 
And the widget works too.

Kind regards,

Harno
