### ISSUE TITLE
Cant find zip code

### ISSUE THREAD

**Issue by henkhuppelschoten** [robertraaijmakers/com.trashchecker#204]
My zipcode is in 'mijn afvalwijzer', i have the afvalwijzer app en on the website it also shows the collecting data.
But if i enter the zipcode in the app configurations and i select 'Mijn afvalwijzer (NL)' than it says: Dit adres wordt niet ondersteund.

**Comment by robertraaijmakers** [comment]
Hi there, do you have an example zip code and house number? Can also be the one of your neighbours :) then I can check why yours doesn’t work.

**Comment by henkhuppelschoten** [comment]
5122GP 94 is the zipcode of my old adres (same city) and doesn't work either

**Comment by henkhuppelschoten** [comment]
Thanxs for looking at it :-)

**Comment by robertraaijmakers** [comment]
@henkhuppelschoten I can't find the issue. I tried with 5122GP 94 myself and it works..
What version of the app are you running?

And can you try with 9821TT number 9 and see if that works?

**Comment by henkhuppelschoten** [comment]
![image](https://github.com/user-attachments/assets/210d3016-004d-4cd5-a7c0-9cd11a91c3cc)
![image](https://github.com/user-attachments/assets/f964675d-14e1-4087-8133-a7ec0c194179)

**Comment by robertraaijmakers** [comment]
Can you try with capital letters?

**Comment by henkhuppelschoten** [comment]
@robertraaijmakers That doesn't work either. 
It's te latsest version

**Comment by henkhuppelschoten** [comment]
Delete the app en reinstall doesn't work also

![image](https://github.com/user-attachments/assets/ecce0642-e119-4bc9-99ec-c74d8f22e65e)

**Comment by robertraaijmakers** [comment]
Sorry, don’t know what is wrong then…
“Works on my machine” and also the unit test is running smoothly… maybe you can manually submit a log and I can check if I can find something in there.. but chances are quite small


![IMG_7751](https://github.com/user-attachments/assets/305f704d-9a92-4cc2-b204-76091320e334)

**Comment by henkhuppelschoten** [comment]
@robertraaijmakers how do i make a log?

**Comment by robertraaijmakers** [comment]
Restart Homey, then go to the settings of the app and enter your zip code and try to save. After that go back to the settings and press the create diagnostics report.

![IMG_7752](https://github.com/user-attachments/assets/2f6dc678-bff8-4c4f-89cb-8b1dddf28fb4)

**Comment by henkhuppelschoten** [comment]
A Homey start up did the job.
My adress is now correct

**Comment by henkhuppelschoten** [comment]
Thanxs fot your help and time
