### ISSUE TITLE
Add support for Saver (Afvalkalender) - active in West-Noord-Brabant, Netherlands

### ISSUE THREAD

**Issue by gerbenp** [robertraaijmakers/com.trashchecker#208]
Hi, is it possible to add support for this?

https://saver.nl/afvalkalender

I have contacted Saver already if they can make the api data available. Don't know if it is possible to get this without the support from Saver if they were not allowed to cooperate. 

I will keep you informed if I know more.

**Comment by gerbenp** [comment]
I discovered these REST API endpoints by examining the network requests in Chrome DevTools. I'm not entirely sure if this list is exhaustive, but here are the unique URLs I've found so far:

https://saver.nl/rest/app/settings
https://saver.nl/zcalendar/pages/page
https://saver.nl/rest/postcode/4715RW
https://saver.nl/adressen/4715RW:1
https://saver.nl/rest/feestdagen/2023-12-26/2025-01-06
https://saver.nl/rest/adressen/0840200000293003/afvalstromen
https://saver.nl/rest/adressen/0840200000293003/kalender/2024

**Comment by gerbenp** [comment]
Tested it, but it hangs on checking my address.

Checked with several postalcodes within the local authority.

I have made an diagnostic report 😊

bc11a6a7-90ef-4643-9eb3-a38105e3a53a

**Comment by robertraaijmakers** [comment]
That is strange. Works here :)
Haven't seen a diagnostic report yet, but don't know how fast that goes normally.

![image](https://github.com/user-attachments/assets/1d8b309c-51a3-4c98-ba5b-a2c215850279)

**Comment by robertraaijmakers** [comment]
I have seen the diagnostics report. I would advise to reboot Homey and try again to see if it works then. I see nothing wrong with the input, but somehow it doesn't seem to handle it properly.

**Comment by gerbenp** [comment]
Still not working after reboot. Here is some more data. 

![Screenshot 2024-12-13 105038](https://github.com/user-attachments/assets/f204c303-e606-4b04-af53-a7ff38058100)
![Screenshot 2024-12-13 104839](https://github.com/user-attachments/assets/f448fc4b-ac0c-448e-a457-c6afef1b2f33)
![Screenshot 2024-12-13 105350](https://github.com/user-attachments/assets/24b38f59-ab40-4e43-b8e7-ccf5ceab6b1f)
![Screenshot 2024-12-13 105341](https://github.com/user-attachments/assets/61175ef8-0056-456e-a19f-29ccd676d779)

New diag report:
f8209d83-96d7-4ee6-873b-ca1b123e7899

**Comment by robertraaijmakers** [comment]
Super weird. Is the behavior the same from the website and from the app?
It seems like some connection issue between client and the saver website. Can't find anything in code and it is running fine in the unit test and on my own mobile device.. hope you can figure out why it can't connect. You don't have any firewalls or stuff at home that might prevent this connection?

**Comment by robertraaijmakers** [comment]
Another user seems to have the same kind of issue, I can't reproduce it on my own laptop and phone. I have tried to mitigate it with the new version (4.1.5). Can you retest it?

**Comment by gerbenp** [comment]
Retested it. Not working :( 

Swapped my ethernet adapter aswell. 

Another debug :)

79ce98a9-0144-4234-88f6-d24421d3c2b2

Have tested the same API on my legacy home assistant dashboard setup but there is it working and retrieving the data.

**Comment by gerbenp** [comment]
Checked also on a mobile hotspot on my iPhone 16 Pro Max (connected on KPN 5G) and is does the same. Just to rule out the firewall and fixed connection.

**Comment by robertraaijmakers** [comment]
Super strange. In de output it says:

Error: connect ETIMEDOUT 2a0a:9fc0:5:0:84:38:237:162:443 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) { errno: -110, code: 'ETIMEDOUT', syscall: 'connect', address: '2a0a:9fc0:5:0:84:38:237:162', port: 443 } 

So does seem to be something with a connection timeout.

I have made a new version (1.0.6) that uses the full rest implementation instead of the iCal implementation that was used before. Maybe this helps... but I don't have high hopes. It still works on my set-up and within the unit tests.. but as shown that doesn't say anything.

**Comment by gerbenp** [comment]
Still not working with 4.1.6. Is it possible that you can force an IPv4 connection for test or built an option for that in?

**Comment by robertraaijmakers** [comment]
Found a way to force IPv4 (hopefully). This weekend, hope that 4.1.9 will fix it for you.

**Comment by gerbenp** [comment]
Yeah, it is working now! Great 😁
