### ISSUE TITLE
 When using source 'Cyclus', no address sync

### ISSUE THREAD

**Issue by idoornhein** [robertraaijmakers/com.trashchecker#209]
Hi,

When entering my postal code in 'Afvalkalender Cyclus (NL)' territory, the 'adres zoeken' message appears indefinitely.
I already restarted the app and Homey, but to no avail.

App versions tested: 4.1.1, 4.1.2, 4.1.3, 4.1.4
Homey version: Pro (early 2023) 12.2.1

Test postalcode: 2914EM   numer: 107

I hope U can find and fix the issue.  

Thx in advance!

**Comment by robertraaijmakers** [comment]
Hi, if I test it myself on my app it works as expected and I get proper values back with the given postal code and zip. I made one more change, because this issue looks a lot like #208.

If you can the new version 4.1.5 that would be great.

If that still doesn't give the proper response, can you try to uninstall the app, do a reboot, then reinstall the app and test again?

**Comment by idoornhein** [comment]
Hi Robert,

Thx for the active support... really appreciated! 

I uninstalled 4.1.5, rebooted my Homey Pro 2023, installed 4.1.5 again (experimental, because the App Store only shows version 4.0.8 at the moment) and tried again. The result is:   'Adres checken' loop again.    The debug part says "Loading collection days" indefinitely. 

Btw The homey pro is connected wired behind a default Nokia modem serving a fiber glass internet connection. Nothing special..

**Comment by robertraaijmakers** [comment]
So, with another source it works? But when you directly select the Cyclus you say it doesn't work?
What do you have selected at the "Cleaning Service" part? Do you put that on "Not-applicable"?

**Comment by idoornhein** [comment]
> So, with another source it works? But when you directly select the Cyclus you say it doesn't work? What do you have selected at the "Cleaning Service" part? Do you put that on "Not-applicable"?

Correct! The exact data I used (which don't work).    Postcode:  2914EM.  Huisnummer: 105.  Land: NL.  Bron: Afvalkalender Cyclus (NL).  Schoonmaakservice: Niet van toepassing.    

And with version 4.1.6. (test) it still doesn't work.  Do you know another way tot test the api from Cyclus manually (outside of Homey)? Just to be sure...

**Comment by robertraaijmakers** [comment]
Don't know. I am absolutely clueless. Have been puzzling the whole weekend to try and find some fixes for this and the other one. I have done a last publish (4.1.9), you can try with that one... Hope it fixes it.

**Comment by idoornhein** [comment]
> Don't know. I am absolutely clueless. Have been puzzling the whole weekend to try and find some fixes for this and the other one. I have done a last publish (4.1.9), you can try with that one... Hope it fixes it.

It works! Now I'm curious as to what did U do to fix this? ![Screenshot_20241216_105216_Homey.jpg](https://github.com/user-attachments/assets/3c97a3ae-8ad0-4b3d-8969-08b9d008927c)

Thanks for all the effort You put in...really appreciated!

**Comment by idoornhein** [comment]
Ps Also the widget works like a charm!

**Comment by robertraaijmakers** [comment]
Great to hear! I forced IPv4 connection... :)

**Comment by idoornhein** [comment]
Hmm.. I saw all the new versions come along and took the plunge, but... the current test (4.2.4) as well as the production (4.2.2) don't work anymore.  It's the same issue as before.    Btw I saw the cleaning service removed from the input possibilities. No clue if that has anything to do with the issue?

**Comment by robertraaijmakers** [comment]
Sorry, things got a bit messed up when reverting to the old version…

**Comment by idoornhein** [comment]
> Sorry, things got a bit messed up when reverting to the old version… 

Haha np i figured as much. Again thx for putting in all the effort!
