### ISSUE TITLE
Adress unavailable

### ISSUE THREAD

**Issue by rowins** [robertraaijmakers/com.trashchecker#21]
I get the message this adress is not supported at settings homey, my adress uses mijn afvalwijzer. When I check my adress at http://www.mijnafvalwijzer.nl/, my adress exists. What can I do to solve this problem?

**Comment by robertraaijmakers** [comment]
Are you sure it exists? And if it exists, does mijnafvalwijzer also display collection days?
Can you please confirm if this issue still persists with version 2.4.0 (currently submitted for beta at Athom).
