### ISSUE TITLE
App crashes on load version 4.1.9

### ISSUE THREAD

**Issue by Witteflits** [robertraaijmakers/com.trashchecker#210]
I received the latest update (4.1.9) and now the app crashes on load. Homey pro (Early 2019)

**Comment by slevin1987** [comment]
Same problem here.

**Comment by robertraaijmakers** [comment]
Yes, I saw, I reported a bug report to Homey because I have no clue how it happens and how I can prevent it.

https://github.com/athombv/homey-apps-sdk-issues/issues/380

**Comment by robertraaijmakers** [comment]
Can you test here? https://homey.app/a/com.trashchecker/test/

**Comment by Witteflits** [comment]
It works again. Thanks for the quick (re)action.

 

Van: Robert ***@***.***> 
Verzonden: donderdag 19 december 2024 15:36
Aan: robertraaijmakers/com.trashchecker ***@***.***>
CC: Witteflits ***@***.***>; Author ***@***.***>
Onderwerp: Re: [robertraaijmakers/com.trashchecker] App crashes on load version 4.1.9 (Issue #210)

 

Can you test here? https://homey.app/a/com.trashchecker/test/

**Comment by robertraaijmakers** [comment]
Thanks! Published :)

Some strange dependency between a public npm package and multiple node versions being present on different Homeys… but all looks good now again.
