### ISSUE TITLE
'Mijn Afvalwijzer' is not working

### ISSUE THREAD

**Issue by Bloodylion2** [robertraaijmakers/com.trashchecker#212]
I noticed I didn't get a notification from Homey today but the Dashboard Widget (which looks very nice btw) was telling tomorrow it was time for rest to get picked up. When running the flow for testing I saw the flowcard for tomorrow was first returning NULL and then Nothing will be picked up. 
I restarted the app and nothing changed. When checking the configuration of the app I saw it says my adres is not supported for 'Mijn Afvalwijzer'. Looks like the official 'Mijn Afvalwijzer' app is being phased out in favor of a new 'Saver' app so they might have changed the API on their side?

**Comment by robertraaijmakers** [comment]
The test version has a saver implementation, you can test it here: https://homey.app/a/com.trashchecker/test/

**Comment by Bloodylion2** [comment]
Looks like it works! Thank you! I see you also added the Cleanprofs check, nice! I did that with my own made homeyscript code now but having it in the app is way better, thank you.
