### ISSUE TITLE
Afvalwijzer stopt

### ISSUE THREAD

**Issue by michaelw85** [robertraaijmakers/com.trashchecker#213]
Hi,

Ik gebruik al een tijd deze homey integratie, dank daarvoor! Ik ben hier echt heel blij mee 😀

Nu kreeg ik gisteren geen melding vanuit mijn flow dus ben ik gaan onderzoeken wat de oorzaak kan zijn. Ik zag dat de widget wel aangaf dat er een ophaaldag was. Via configuratie krijg ik de melding dat mijn postcode niet (meer) wordt ondersteund en zie ik het volgende nieuwsbericht:

https://mijnafvalwijzer.nl/nl/4661ck/nieuws/#nieuws

> 23-11-2024
Deze Afvalwijzer app stopt per 1 januari 2025. Download nu de nieuwe Saver app.

Dit lijkt mij geen toeval.

Moet ik hiervoor de guide gaan volgen om een nieuwe api in de app te integreren of zou de bestaande een update moeten krijgen?

Wat mij opviel is dat de postcode check op mijn werk nog wel goed gaat via dezelfde api. Dit is wel een andere gemeente,. Maar een collega deelde het nieuwsbericht met mij dus had ik verwacht dat ook die postcode check zou falen.

**Comment by robertraaijmakers** [comment]
Hi, zie ook #212 

The test version has a saver implementation, you can test it here: [https://homey.app/a/com.trashchecker/tes](https://homey.app/a/com.trashchecker/test/)

**Comment by michaelw85** [comment]
Dankjewel, de nieuwe versie werkt met de saver implementatie! 🥳
