### ISSUE TITLE
Unable to add device into Homey

### ISSUE THREAD

**Issue by johhemmi** [robertraaijmakers/com.trashchecker#214]
Hi
I have installed the Trashcan Reminder into my Homey and it is visible under Apps
But when I try to add this as a new device, and under brands it is not visible.

Tried to uninstall and install again but it will not show
I am using Homey Pro (Early 2023) version 12.2.1 

Have I done something wrong, or do I need to do something else?

Br
Johnny

**Comment by robertraaijmakers** [comment]
Hi @johhemmi,

Please check out the set-up guide.
https://robertraaijmakers.github.io/com.trashchecker/settings.html

Let me know if you need more info
