### ISSUE TITLE
Add data from collecting "Oud Papier"

### ISSUE THREAD

**Issue by rexvdb** [robertraaijmakers/com.trashchecker#25]
I use the data for collecting trash from "Mijn Afvalwijzer"

Mijn afvalzijzer contents all data except "Papier". They collect this once a month but not in the same week every month. Then it is the 2nd Saturday and a month later the 3th. Is it may be possible in a new version to fill the date they collect the paper for example 22 September, 27 October, 24 November?

Best regards,
 Rex

**Comment by rexvdb** [comment]
I use the data for collecting trash from "Mijn Afvalwijzer"

Mijn afvalzijzer contents all data except "Papier". They collect this once a month but not in the same week every month. Then it is the 2nd Saturday and a month later the 3th. Is it may be possible in a new version to fill the date they collect the paper for example 22 September, 27 October, 24 November?

Best regards,
Rex

**Comment by robertraaijmakers** [comment]
I use mijn afvalwijzer as well and for me it displays the papier just fine. Can you give me an example address?

**Comment by rexvdb** [comment]
Hi Robert,
I use 5464pe.
Best regards,Rex



Met vriendelijke groeten,Rex van den Broek
Verzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: Robert <notifications@github.com> Datum: 11-10-18  21:21  (GMT+01:00) Aan: "robertraaijmakers/com.trashchecker" <com.trashchecker@noreply.github.com> Cc: rexvdb <rex@vdbroek.nl>, Author <author@noreply.github.com> Onderwerp: Re: [robertraaijmakers/com.trashchecker] Add data from collecting
  "Oud Papier" (#25) 
I use mijn afvalwijzer as well and for me it displays the papier just fine. Can you give me an example address?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/robertraaijmakers/com.trashchecker","title":"robertraaijmakers/com.trashchecker","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/robertraaijmakers/com.trashchecker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@robertraaijmakers in #25: I use mijn afvalwijzer as well and for me it displays the papier just fine. Can you give me an example address?"}],"action":{"name":"View Issue","url":"https://github.com/robertraaijmakers/com.trashchecker/issues/25#issuecomment-429085855"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/robertraaijmakers/com.trashchecker/issues/25#issuecomment-429085855",
"url": "https://github.com/robertraaijmakers/com.trashchecker/issues/25#issuecomment-429085855",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [robertraaijmakers/com.trashchecker] Add data from collecting \"Oud Papier\" (#25)",
"sections": [
{
"text": "",
"activityTitle": "**Robert**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@robertraaijmakers",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"robertraaijmakers/com.trashchecker\",\n\"issueId\": 25,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"robertraaijmakers/com.trashchecker\",\n\"issueId\": 25\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/robertraaijmakers/com.trashchecker/issues/25#issuecomment-429085855"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 383068198\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by robertraaijmakers** [comment]
So i checked the address and Mijn Afvalwijzer doesn't have any collection days for Papier.
I took a random house number (sorry if it's accidentally your house) https://www.mijnafvalwijzer.nl/nl/5464PE/205/. Here you can see that there is no paper listed.

**Comment by rexvdb** [comment]
Hi Robert,  is het mogelijk dat ik gewoon Mijn Afvalwijzer blijf gebruiken en het oud papier er met de hand invoer. Of schakelt de keuze uit Mijn Afvalwijzer als je met de hand data gaat invoeren?
