### ISSUE TITLE
address invalid

### ISSUE THREAD

**Issue by hrc007** [robertraaijmakers/com.trashchecker#27]
My zipcode (2953em)  is currently not working anymore. it was working before (1 mounth ago) on the HVC calendar.
My zipcode should have a match with the HVC calendar, but when i do a lookup now with the app it has a match with RD4 calendar. 

Homey firmware: 1.5.13-rc.11
app version: v.2.3.3

Regards
Henk

**Comment by robertraaijmakers** [comment]
Hi Henk,

You can change the drop down with APIs to chose from manually to HVC to override the default selection.

Hope this helps.

**Comment by hrc007** [comment]
Hi Robert,
When i select the hvc calendar manually is says : this addess is not supported (in dutch)

**Comment by Olof007** [comment]
Same issue (living in Zeewolde, HVC). Above workarround is not working. I can choose HVC of course but than I dont get alerts because 'This address is not supported'.
I like this piece of software a lot. If I can help with testing let me know. I dont have programming experience.

**Comment by robertraaijmakers** [comment]
Version 2.4.2 has been submitted for review. Apparently HVC changed it's website and it's API, so the retrieval of this data had to be changed as well. Hopefully the beta app will be approved soon and then you can test if it works.

**Comment by hrc007** [comment]
Hi Robert, thanks, if it comes available i will test it!

**Comment by Olof007** [comment]
Hi Robert, I have tested beta 2.4.4 with the following info 3892HD, 71, source HVC But it stays at checking address.... After a refresch, all filled in fields are empty again. Already tried a reinstall. Thanks so far, I will test again if needed. Olof ---- On Sat, 17 Nov 2018 17:45:52 +0100 Robert <notifications@github.com> wrote ---- Version 2.4.2 has been submitted for review. Apparently HVC changed it's website and it's API, so the retrieval of this data had to be changed as well. Hopefully the beta app will be approved soon and then you can test if it works. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by hrc007** [comment]
Hi Robert I also have tested the new version (2.4.4) but the same results as Olof007.

**Comment by eelco2k** [comment]
i'm getting this error when trying with an HVC postalcode: The app has crashed an this is the debuglog:
```
Stack trace: /trashapis.js:299 var urlRequest = "https://" + baseUrl + "/adressen/" + postcode + ':' + housenumber; ^ ReferenceError: housenumber is not defined at newGeneralAfvalkalandersNederland (/trashapis.js:299:77) at Object.inzamelkalenderHVC [as execute] (/trashapis.js:717:2) at TrashcanReminder.updateAPI (/app.js:598:21) at Object.fn (/api.js:13:23) at ManagerApi._onRest (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/api.js:1:729) at _eventListeners.filter.forEach.t (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1219) at Array.forEach (<anonymous>) at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1196) at emitTwo (events.js:126:13) at process.emit (events.js:214:7) Exit code: 1 Exit signal: null
```

**Comment by robertraaijmakers** [comment]
Thanks, I'm currently really busy and already found the fix but haven't gotten any time at home to check it and ship it. Hope to get it out before the holidays with all the strange pick up dates.

**Comment by eelco2k** [comment]
No problem for now I’ve installed it via developer mode. With the changes. 
Have a nice holiday!

**Comment by robertraaijmakers** [comment]
Version 2.4.5 pending approval.

**Comment by Olof007** [comment]
It works again! Thanks a lot, very usefull app.


 ---- On Wed, 12 Dec 2018 19:38:12 +0100 Robert <notifications@github.com> wrote ----
