### ISSUE TITLE
Broken Reminders

### ISSUE THREAD

**Issue by Veldkornet** [robertraaijmakers/com.trashchecker#3]
So I switched from Trashcan Reminders 1.0 to Trashcan Reminders 2.0 and updated my flows with exactly the same information as in 1.0. But something seems to be off.... I got a reminder that rest and GFT are collected today when they are not....

So basically I have a flow that says, if it's 07:00 and GFT is collected today, then send a message.
GFT:
![gft](https://user-images.githubusercontent.com/10297361/30469509-ef22a3d6-99f0-11e7-80a0-3599f869fe5f.PNG)

Same for rest.
Rest:
![rest](https://user-images.githubusercontent.com/10297361/30469531-fac80122-99f0-11e7-866e-b2616ef02e80.PNG)

However after updating yesterday, today I received notifications for both, and both are incorrect since GFT was already yesterday, and rest is only next week. If I look at the tag though, it says that there is nothing for today.....
Tag:
![tag](https://user-images.githubusercontent.com/10297361/30469535-fd6ac66c-99f0-11e7-8b7f-e284bc2c1cb7.PNG)

**Comment by robertraaijmakers** [comment]
Thanks for reporting. I do have some questions to see if I can find the root cause of this issue:
- Do you use the custom settings or did you enter a postal code? (if you are using a postal code, are you willing to share, house number isn't needed, I will pick a random one)
- Are your Homey time settings correct?
- Did you remove the Trashcan Reminder 1.0?

**Comment by Veldkornet** [comment]
- I entered a postal code (2728AK)
- Yes
- Yes

**Comment by robertraaijmakers** [comment]
Is fixt in >= 2.0.6

**Comment by robertraaijmakers** [comment]
Can you check somewhere this week if it is working in the latest beta? (2.1.1)

**Comment by Veldkornet** [comment]
Just tested with a test flow, seems to be okay. I'll keep it scheduled though just to double check.

However, I did notice something else while trying to test it.

I created a flow which lets me know of trash is being collected "overmorgen". 
If GFT is selected, the flow stops (this is expected).
If REST is selected, the flow continues (Also expected) but then the message that gets sent is from today.

So basically that "Nothing is scheduled for pickup", where as I would expect it to say that REST is scheduled.

![overmorgen](https://user-images.githubusercontent.com/10297361/30585772-30ea8960-9d2e-11e7-9076-1699406091f3.PNG)

Aslo, is there anyway to have different texts for vandaag, morgen, and overmorgen?

![image](https://user-images.githubusercontent.com/10297361/30585968-bf38560c-9d2e-11e7-9ed8-b50226426a43.png)

**Comment by robertraaijmakers** [comment]
To change the global tag value you can type any text you want in the text boxes on the setting page. So if you type there day after tomorrow instead of today you are done. If you want the labels to correspond with the trash that is collected the day after tomorrow, then change the Dropbox to day after tomorrow (overmorgen). And the label will be filled with the type that is collected the day after tomorrow.

**Comment by Veldkornet** [comment]
Understood. Although it would be easier if you didn't need to keep them in sync :)

What if I wanted two flows, one for today and one for tomorrow? :)

**Comment by robertraaijmakers** [comment]
Then you have an issue ;)

The thing with global tags is that they can't be dynamically set based on something in the 'if' column.

The only workaround would be if I implement three global tags. But that would mean 3x more input boxes with text. 3x more effort of changing them as a user.

**Comment by mhjansen79** [comment]
I still have the issue. But only for plastic.... You see the condition comes back negative, but the actions still take place. 

<img width="1174" alt="screen shot 2017-09-19 at 16 59 31" src="https://user-images.githubusercontent.com/24822406/30599211-0fea1ee6-9d5c-11e7-8e8e-fd15b581886d.png">

**Comment by robertraaijmakers** [comment]
Does it say anything if you hover over the red cross? What Trashcan 2.0 version are you using and on what Homey version are you?

**Comment by mhjansen79** [comment]
Hi Robert, 

The Red Cross doesn't say anything. My settings are as follows:
<img width="512" alt="screen shot 2017-09-19 at 19 30 21" src="https://user-images.githubusercontent.com/24822406/30606211-364c2fce-9d71-11e7-97ef-e606fed7a24e.png">
<img width="204" alt="screen shot 2017-09-19 at 19 30 37" src="https://user-images.githubusercontent.com/24822406/30606215-3916f40a-9d71-11e7-8637-a69aeee6dfee.png">

Thanks for your quick response!

Marc

**Comment by Veldkornet** [comment]
Indeed I can confirm what @mhjansen79 says.

For me, the following work:
Something
Rest
GFT

The following send a message even if the condition is false:
Paper
Plastic
PMD
Textiel

**Comment by robertraaijmakers** [comment]
For me it only happens with PMD and Textiel... weird. Will have a look soon.

**Comment by Veldkornet** [comment]
Something still isn’t right. Today rest is being picked up, but that’s not the message I got. 

The flow I had was:
IF it’s 07:00 and Rest is being picked up today, then send the message. 


The message was sent which is great, but the message was from the “nothing message....

I also had a second flow as a test Which was:
IF it’s 07:00 and anything is being picked up today, then send the message. 

But here it also sent the “nothing” message....

**Comment by robertraaijmakers** [comment]
That's strange, can you check what the global label says when you search for it in the flow?
And what happens if you re-enter your postalcode & housenumber, does the global label change to the correct value afterwards?

**Comment by Veldkornet** [comment]
Even after saving my address again, the global tag still says that nothing is planned for today.

**Comment by robertraaijmakers** [comment]
I probably found the bug for the tag not being updated (overnight and after saving an address). So I made a couple of fixes:
- After changing the settings, the global tag is updated;
- You can now see the collection days when you press the Green Text after changing the settings;
- You can see which API is used for you postal code;
- The trash collection days are only refreshed on Saturday Nights (this to prevent that notifications aren't send on the day itself, my provider for instance, removes the collection date when the day is equal to today... so I never received notifications since they were already removed from the API).

These improvements can be found in the beta github version. I will check if I get updates myself next monday morning. And if so, I will submit the changes to the store.

**Comment by rjbaat** [comment]
I have the same problem. Paper, GFT and Rest is giving me api respons but not PMD. BTW why is my address not recognised anymore on the mijnafvalwijzer in the app? When i go to the site i get a good respons: http://www.mijnafvalwijzer.nl/. I believe this was working before.

**Comment by robertraaijmakers** [comment]
@rjbaat which version do you have installed currently?
And is the response green or orange on mijnafvalwijzer.nl?

**Comment by mhjansen79** [comment]
just an update from my side. As of today, after the latest update (2.1.2), all my flows and notifications are working as intended. (at least they aren't triggering when they shouldn't be, I'll have to wait until the actual trash days to see if they fire correctly)

**Comment by rjbaat** [comment]
@robertraaijmakers 
Version v2.1.2 And with my address filled its getting red with: Dit adres wordt niet ondersteund. This addres is working on mijnafvalwijzer.nl.

**Comment by robertraaijmakers** [comment]
@rjbaat Is the address on mijnafvalwijzer.nl green or orange when you enter is. Not in the app settings of the Homey app.

![image](https://user-images.githubusercontent.com/1773099/30865247-61a20de6-a2d6-11e7-80a2-e9f568e6af17.png)

**Comment by rjbaat** [comment]
@robertraaijmakers On the site its green.

**Comment by robertraaijmakers** [comment]
Can you add an example postalcode & housenumber so I have an address to test with in the following issue: https://github.com/robertraaijmakers/com.trashchecker/issues/6. Thanks.

**Comment by Veldkornet** [comment]
Was the issue supposed to be fixed on 2.1.2?

I got a push today that nothing is being picked up although GFT is scheduled.

**Comment by robertraaijmakers** [comment]
Well weird, I don't understand why your global tag isn't updated. The date seems to be correct as you get a push message. I will try and find out what happens with the global tag (it should be updated once every 24 hours).
What timezone is your Homey in?

**Comment by Veldkornet** [comment]
timezone | Europe/Amsterdam

**Comment by Veldkornet** [comment]
My settings updated themselves to use "Recyclemanager" instead of "mijnafvalwijzer" after setting it to "unknown", and now it appears to show the correct global tag. Will have to wait a week to know for sure though :)

Although I see I've now uncovered #6 as well...

**Comment by robertraaijmakers** [comment]
After the update and resetting your settings this should be solved. Please follow the instructions in this post if the reset doesn't work directly: https://forum.athom.com/discussion/comment/59575/#Comment_59575

**Comment by Veldkornet** [comment]
Looks good, still working form me.

Both grey and green have been correctly reported.

**Comment by robertraaijmakers** [comment]
Added a fix to cache the data for a week. This should resolve the empty reminders and some other long running issues. Will submit the beta branch to the store somewhere next week after I've done some testing here at home.
