### ISSUE TITLE
[REQ] Custom URL

### ISSUE THREAD

**Issue by Radiotechniman** [robertraaijmakers/com.trashchecker#31]
Being able to have the app calculate the next pickup date is great, but this christmas period i noticed the GAD added some extra (non standard) dates and because of this I missed a pickup.
I've found the url where this data is published and created a PHP page to translate the data in the required format (happy to share) but I would like to be able to point this Homey app to this page..

Would this be possible?

**Comment by robertraaijmakers** [comment]
Technically this would be possible indeed. But I'm not going to build it, so then someone from the community or yourself should create a pull request with this functionality.

**Comment by robertraaijmakers** [comment]
It's been a while. But with the Christmas period around the corner I implemented the GAD (Gooi & Vechtstreek) afvalkalender in the app. So no need for a custom API, the native GAD is now supported in the Homey App as of version 2.6.3!

**Comment by Radiotechniman** [comment]
great, thanks!



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
10/11/19,
10:39:21 AM

Op do 10 okt. 2019 om 22:11 schreef Robert <notifications@github.com>:
