### ISSUE TITLE
Not receiving all data

### ISSUE THREAD

**Issue by kevvie** [robertraaijmakers/com.trashchecker#33]
In the debug section of the app I cannot see the dates when the pmd will be collected. I'm using "afvalwijzer"

**Comment by robertraaijmakers** [comment]
What for dates do you see when you check it on the Afvalwijzer website? And do you have a zip code for reference so I can see why it doesn't work for your zipcode.

**Comment by kevvie** [comment]
On the website I can see 4 types of pickups: gft, pmd, rest and paper. In the debug I can only find gft, rest and paper. My zip code is 4941LD, 75.

**Comment by robertraaijmakers** [comment]
I've found the solution and the issue will be fixt in next beta release. Will provide the version number when available.

**Comment by robertraaijmakers** [comment]
I've implemented the new trash type for afvalwijzer and submitted version 2.5.0 to the Athom App Store as BETA. Please test it when it comes available.

Donations are welcome: https://www.paypal.me/RobertRaaijmakers
