### ISSUE TITLE
Address not supported anymore (meerlanden)

### ISSUE THREAD

**Issue by ruudmens** [robertraaijmakers/com.trashchecker#34]
The app was working fine until the second week of December. Tried rebooting Homey, reinstalled the app, but somehow I get to error "address not supported" while it has worked for almost a year.

- Debug data shows last retrieved data
- Postcode / address: 2182DH 43
- API: Meerlanden

I checked the Meerlanden calendar self, and there I still can retrieve the data.

**Comment by robertraaijmakers** [comment]
Fixt and will be updated in next beta release. I will provide the version number when available.

**Comment by robertraaijmakers** [comment]
I've fixt and implemented the new API for Meerlanden and submitted version 2.5.0 to the Athom App Store as BETA. Please test it when it comes available.

Donations are welcome: https://www.paypal.me/RobertRaaijmakers

**Comment by robertraaijmakers** [comment]
Should work again with 2.5.2
