### ISSUE TITLE
API 's-Hertogenbosch not working anymore, new API available.

### ISSUE THREAD

**Issue by tfreriks** [robertraaijmakers/com.trashchecker#35]
Postal code: 5247JV 
No: 5

Used to work, but not last year.

Could you please add this new API?

https://www.denbosch.afvalstoffendienstkalender.nl/nl/5247jv/5/ 

It is for the Dutch city 's-Hertogenbosch and surrounding cities.

**Comment by robertraaijmakers** [comment]
I've implemented this new API in the BETA version 2.5.0. Please test it when it comes available.
Donations are welcome: https://www.paypal.me/RobertRaaijmakers

**Comment by tfreriks** [comment]
Great!

Just installed 2.5.0

Will test next Tuesday when I have positive data (my trash will be picked up wedesday)

**Comment by tfreriks** [comment]
Works like a charm!! (Getting all reminders for two weeks now en put my trash out in time... 😊)

Thx @robertraaijmakers !
