### ISSUE TITLE
API Afvalkalender Venray

### ISSUE THREAD

**Issue by Zwansy** [robertraaijmakers/com.trashchecker#38]
Isn't working anymore since a couple of weeks.
Whenever I click the link in the description, it comes out on a page which doesn't exist anymore.

**Comment by Zwansy** [comment]
Hi Robert,
I’ve updated the app to version 2.5.1, but this version crashes when the app starts.
Is there anything I can do?

**Comment by robertraaijmakers** [comment]
Should work again with 2.5.2
