### ISSUE TITLE
KEEP IT SIMPLE !!!

### ISSUE THREAD

**Issue by chrisboer** [robertraaijmakers/com.trashchecker#4]
![afbeelding](https://user-images.githubusercontent.com/23163409/30524131-187ecce2-9bee-11e7-9f63-f93f3922099a.png)

**Comment by chrisboer** [comment]
![afbeelding](https://user-images.githubusercontent.com/23163409/30524139-3854bae0-9bee-11e7-904f-3d1db34c930e.png)

**Comment by robertraaijmakers** [comment]
KEEP IT UNDERSTANDABLE!!

**Comment by Bozo29** [comment]
Keep it Simple:
![image](https://user-images.githubusercontent.com/25449223/30644635-491180d0-9e13-11e7-96d5-d4d4ec4f47b6.png)
