### ISSUE TITLE
[REQ] Add new frequency: once per 2 months

### ISSUE THREAD

**Issue by MrBlue90** [robertraaijmakers/com.trashchecker#40]
Hi there,

In my city, we have a so-called BEST bag; a bag where you can offer book, clothes, electronics and toys.
https://www.rd4.nl/inwoners/algemeen/containers-en-zakken/best-tas

This bag gets collected **every last Friday per 2 months**.

Unfortunately, I can't find a setting on how to schedule this manually.
Last Friday of the month is the closest one I got, but that results in incorrect notifications.

Any chance you can add this option?

Thanks,
Rick

**Comment by robertraaijmakers** [comment]
Hi,

You can ask the developer of the RD4 API if they will be able to add this best-tas in their API. Maybe they can log it as Textile so that you can generate a specific notification.

With kind regards, Robert

**Comment by robertraaijmakers** [comment]
Will be added in 2.6.0
