### ISSUE TITLE
ophalen adres Circulus Berkel werkt niet.

### ISSUE THREAD

**Issue by bdeelman** [robertraaijmakers/com.trashchecker#41]
Na het invoeren van de postcode en huisnummer en Afvalkalender Circulus Berkel blijft hij staan op adres checken...

Ons huisnummer is officieel 118b, meerdere opties gebruikt 118, 118b, 118B, 118 b en 118 B. 
Wat voer ik in als huisnummer in de Homey app?

Groet,
Bert

**Comment by robertraaijmakers** [comment]
Beste, wat voert u in op de website van https://mijn.circulus-berkel.nl/login-of-geef-een-adres-op/ zelf? En komen daar wel de juiste gegevens uit terug?

**Comment by bdeelman** [comment]
Dag Robert,

Jij ik krijg de juiste gegevens bij Circulus terug, wel met een extra stap.
Welke toevoeging ik ook invul ik krijg een popup met keuze. Ik moet kiezen
tussen 118 a of 118 b (let op de spatie tussen huisnummer + toevoeging).
Als ik 118 / 118 b / 118 B / 118b / 118B invul altijd de vraag welk nummer.

Ik heb het opgelost om het adres van de overburen (zonder toevoeging) te
nemen.

Groet,
Bert



Op za 23 mrt. 2019 om 10:21 schreef Robert <notifications@github.com>:

**Comment by robertraaijmakers** [comment]
Bijzonder, maar mooi dat het gelukt is door een ander adres te pakken!
