### ISSUE TITLE
enter own dates

### ISSUE THREAD

**Issue by llentjes** [robertraaijmakers/com.trashchecker#46]
Would it be an option to maintaim a list of dates on my own? This way we would not be dependend on the api of the several websites.

**Comment by robertraaijmakers** [comment]
Yes, there is an option. It is a checkbox on the settings page that says "enter manual dates" and there you can provide manual options.

**Comment by llentjes** [comment]
I am aware of this option. But what i I mean is that one can enter dates instead of a cycle.
for example: 
GFT:
5-1-2019
15-1-2019
29-1-2019
and so on.

**Comment by robertraaijmakers** [comment]
I will have a look, but don't think it will be added in the upcoming months by me. Maybe someone from the community will contribute if they feel that this is a necessary addition.

**Comment by robertraaijmakers** [comment]
The manual option won't be added. But two new date options will be added: once every eight weeks and an once every other month option which enables you to enter advanced schedules.

**Comment by robertraaijmakers** [comment]
Two new manual options will be available in version 2.6.0
