### ISSUE TITLE
Gemeente Hellendoorn cannot be used anymore (unsupported zip code)

### ISSUE THREAD

**Issue by luuk-harmeling** [robertraaijmakers/com.trashchecker#52]

**Comment by luuk-harmeling** [comment]
When i select "Gemeente Hellendoor" with my own valid zip code and house number the error "unsupported zip code" is prompted.

**Comment by robertraaijmakers** [comment]
Do you have a zip code that should be valid according to the gemeente hellendoorn site?

**Comment by luuk-harmeling** [comment]
Yes , 7441DL

**Comment by robertraaijmakers** [comment]
Thanks. It looks like they changed their complete implementation. It looks quite similar now to the Twente implementation. I will see what I can do but probably will be somewhere after the summer.

**Comment by luuk-harmeling** [comment]
Hey Robert,

I’m getting married in a week, i might be aboe to help after our honeymoon. Ill be around at july.
Im a software engineer myself so.

**Comment by robertraaijmakers** [comment]
Congratulations! Enjoy the big day and the honeymoon! Will be in touch when there is time ;)

**Comment by rhannink** [comment]
Hello, I wrote the original part for retreiving gemeente Hellendoorn and twente millieu. They have changed their API and I already did the reverse engineering part, but they have added an extra step where you have to pick your exact housenumber from a list is there’ s a letter part ( eg. 36,36a and 36b). I have to find some time to make the adjustments...

Gr. Remco

**Comment by nilsaw11** [comment]
And....  Something moving yet?  Still "adres wordt niet ondersteund " and that's to bad.... 
Love to see this working again. 
Best regards from nijverdal ; -)

**Comment by rhannink** [comment]
Hello,
In the meantime I figuren out the POST calls to het the trashcalendar;

1- POST to:

`https://wasteapi.2go-mobile.com/api/FetchAdress` 

with Body 

`{"postCode":"7441AA","houseNumber":"121","companyCode":"24434f5b-7244-412b-9306-3a2bd1e22bc1","houseLetter":""}`	

Then you get back a list with all possible numbers/letters:

```
{
    "userMessage": {
        "type": null,
        "messageCode": 0,
        "description": null
    },
    "ExtraOption": {
        "$type": "System.Dynamic.ExpandoObject, System.Core"
    },
    "dataList": [
        {
            "UniqueId": "5516e50e3bf07dcac84a2be2cf2233f691f09f3f",
            "Street": "Rijssensestraat",
            "HouseNumber": "121",
            "HouseLetter": "1",
            "HouseNumberIndication": null,
            "HouseNumberAddition": "",
            "ZipCode": "7441AA",
            "City": "Nijverdal",
            "Community": null,
            "AddressType": null,
            "Floor": null,
            "AddressUniqueId": 0,
            "AddressUnique": null
        },
        {
            "UniqueId": "3e392dcd625f760dbaefc61b3a9a6567a6628908",
            "Street": "Rijssensestraat",
            "HouseNumber": "121",
            "HouseLetter": "2",
            "HouseNumberIndication": null,
            "HouseNumberAddition": "",
            "ZipCode": "7441AA",
            "City": "Nijverdal",
            "Community": null,
            "AddressType": null,
            "Floor": null,
            "AddressUniqueId": 0,
            "AddressUnique": null
        }
],
    "intDataList": null,
    "data": null,
    "status": true,
    "messageCode": 107,
    "pdfResponse": null,
    "token": null,
    "ID": null,
    "invalidParameters": null,
    "total": 0,
    "messageToString": null
} 
```	
Choose the right one and with the correct UniqueId do a second POST to:

`https://wasteapi.2go-mobile.com/api/GetCalendar`

With body:

`{"companyCode":"24434f5b-7244-412b-9306-3a2bd1e22bc1","startDate":"2019-09-01","endDate":"2019-12-31","uniqueAddressID":"5516e50e3bf07dcac84a2be2cf2233f691f09f3f"}`

Then you get back a list of all pick-up dates:
```
{
    "userMessage": {
        "type": null,
        "messageCode": 0,
        "description": null
    },
    "ExtraOption": {
        "$type": "System.Dynamic.ExpandoObject, System.Core"
    },
    "dataList": [
        {
            "pickupDates": [
                "2019-09-03T00:00:00",
                "2019-09-10T00:00:00",
                "2019-09-17T00:00:00",
                "2019-09-24T00:00:00",
                "2019-10-01T00:00:00",
                "2019-10-08T00:00:00",
                "2019-10-15T00:00:00",
                "2019-10-22T00:00:00",
                "2019-10-29T00:00:00",
                "2019-11-05T00:00:00",
                "2019-11-12T00:00:00",
                "2019-11-19T00:00:00",
                "2019-11-26T00:00:00",
                "2019-12-03T00:00:00",
                "2019-12-10T00:00:00",
                "2019-12-17T00:00:00",
                "2019-12-24T00:00:00",
                "2019-12-31T00:00:00"
            ],
            "pickupType": 0,
            "_pickupType": 0,
            "_pickupTypeText": "GREY",
            "description": "Null"
        },
        {
            "pickupDates": [
                "2019-09-03T00:00:00",
                "2019-09-10T00:00:00",
                "2019-09-17T00:00:00",
                "2019-09-24T00:00:00",
                "2019-10-01T00:00:00",
                "2019-10-08T00:00:00",
                "2019-10-15T00:00:00",
                "2019-10-22T00:00:00",
                "2019-10-29T00:00:00",
                "2019-11-05T00:00:00",
                "2019-11-12T00:00:00",
                "2019-11-19T00:00:00",
                "2019-11-26T00:00:00",
                "2019-12-03T00:00:00",
                "2019-12-10T00:00:00",
                "2019-12-17T00:00:00",
                "2019-12-24T00:00:00",
                "2019-12-31T00:00:00"
            ],
            "pickupType": 10,
            "_pickupType": 10,
            "_pickupTypeText": "PACKAGES",
            "description": "Null"
        },
        {
            "pickupDates": [
                "2019-09-04T00:00:00",
                "2019-09-11T00:00:00",
                "2019-09-18T00:00:00",
                "2019-09-25T00:00:00",
                "2019-10-02T00:00:00",
                "2019-10-09T00:00:00",
                "2019-10-16T00:00:00",
                "2019-10-23T00:00:00",
                "2019-10-30T00:00:00",
                "2019-11-06T00:00:00",
                "2019-11-13T00:00:00",
                "2019-11-20T00:00:00",
                "2019-11-27T00:00:00",
                "2019-12-04T00:00:00",
                "2019-12-11T00:00:00",
                "2019-12-18T00:00:00",
                "2019-12-23T00:00:00",
                "2019-12-27T00:00:00"
            ],
            "pickupType": 2,
            "_pickupType": 2,
            "_pickupTypeText": "PAPER",
            "description": "Null"
        }
    ],
    "intDataList": null,
    "data": null,
    "status": true,
    "messageCode": 107,
    "pdfResponse": null,
    "token": null,
    "ID": null,
    "invalidParameters": null,
    "total": 0,
    "messageToString": null
}
```

If I have Some time left in the coming weeks, I Will try to change the current code in the TrashAPI. The code for Twente milieu is exactly the Same, only the companyCode differs.

`8d97bb56-5afd-4cbc-a651-b4f7314264b4`

Gr. Remco

**Comment by robertraaijmakers** [comment]
Hi Remco,

Thanks for finding all the information and how the requests need to work together. I have implemented the Twente Milieu and Gemeente Hellendoorn based on the requests you found and they seem to work! I will check-in the changes in GitHub tonight and will submit the app for review directly. Hopefully it's in the beta channel after the weekend and then somewhere next week I will submit it to the master as well.

With kind regards, Robert

**Comment by rhannink** [comment]
Wow Robert,
That is fast. Probably would have cost me a few days, not being a proper software engineer.
Good to see that not 2 but even 3 new areas are now supported again.

Thanks.....

**Comment by rhannink** [comment]
Just installeer version 2.6.3 and it works like a charm. Only testen Gemeente Hellendoorn. 

I am also using the labels now. So everything is now packed in one flow instead of 4 flows. The evening before pick-up we get a push Notification and a warning via Google Home.

Thanks again, Great app.

**Comment by robertraaijmakers** [comment]
How did you link it to your Google Home? Does Google Home notify you or does Homey notify you?

**Comment by rhannink** [comment]
Via the Google TTS app in Homey:

<img width="387" alt="image" src="https://user-images.githubusercontent.com/1661824/66639890-1825a000-ec18-11e9-82e4-84b563d0a693.png">

**Comment by robertraaijmakers** [comment]
Cool! Didn't know that exists :)

**Comment by rhannink** [comment]
And my label settings:

![image](https://user-images.githubusercontent.com/1661824/66639990-473c1180-ec18-11e9-89a6-af449072e563.png)
