### ISSUE TITLE
zip code no longer accepted DAR afvalkalender Nijmegen

### ISSUE THREAD

**Issue by snoekDS** [robertraaijmakers/com.trashchecker#53]
Hi Robert ,

Can you please check whether the inrface to the DAR afvalkalender is still valid ?
My previous working zip code is no longer accepted by the setting page.

**Comment by robertraaijmakers** [comment]
Can you provide a zip code that should work with the afvalkalender?

**Comment by snoekDS** [comment]
6531KD

Op do 16 mei 2019 om 15:52 schreef Robert <notifications@github.com>:

**Comment by snoekDS** [comment]
https://afvalkalender.dar.nl/adres/6531KD:72


Op do 16 mei 2019 om 15:54 schreef Wybe Boelders <wybe.boelders@gmail.com>:

**Comment by robertraaijmakers** [comment]
Thanks. They changed their API, I will have to implement the new API. Will see what I can do.

**Comment by snoekDS** [comment]
Hi Robert

Would be nice , I like this app very much and appreciate homey telling me
what to do.


Op do 16 mei 2019 om 16:05 schreef Robert <notifications@github.com>:

**Comment by robertraaijmakers** [comment]
Will be fixt with 2.5.5, currently submitted for review to the app store as beta
