### ISSUE TITLE
[REQ] PDM alias

### ISSUE THREAD

**Issue by PhAnt0mFS** [robertraaijmakers/com.trashchecker#54]
In Zutphen (Circulus-berkel) PDM bags are collected together with glass in the so called "zwarte kratje"
In the debug it's called ZWAKRA so it isn't recognized as PDM. 

Is it possible to add an alias to translate ZWAKRA to PDM?

**Comment by robertraaijmakers** [comment]
Pushed to store. ZWAKRA is now recognised as PMD.
