### ISSUE TITLE
Afvalwijzer

### ISSUE THREAD

**Issue by susannahilberdink** [robertraaijmakers/com.trashchecker#55]
Hey,

In de afvalwijzer zijn de data van rest en papier omgedraaid of de tekst rest en papier omgedraaid. Inhoudend dat bij de data van het papier, de tekst rest staat en Vice versa.
De datas kloppen op deze manier dus niet

Groetjes Susanna

**Comment by robertraaijmakers** [comment]
Hi Susanna,
Heb je een postcode waar dit het geval voor is en waar ik dit mee kan testen?
Mvg, Robert

**Comment by susannahilberdink** [comment]
Hey hallo,

9681TP huisnummer 5,

Kerkelaan 5 in midwolda.

De data zijn niet correct overgenomen😬

Groetjes Susanna

**Comment by robertraaijmakers** [comment]
Beste Susanne,

In de mobiele app zie ik dezelfde data terugkomen als ik het ophaal als op https://www.mijnafvalwijzer.nl/nl/9681TP/5/

Ik ga er dan ook vanuit dat er een fout zat in de data van mijn afvalwijzer en dat de app prima werkt.

Met vriendelijke groet,
Robert

**Comment by susannahilberdink** [comment]
Goedenavond,

En toch komt dit niet overeen.
Bijgevoegd daarom de foto’s. Zowel uit Homey, als uit de afvalwijzer app.

**Comment by robertraaijmakers** [comment]
Hi Suzanne, zou je de screenshots nog eens kunnen uploaden. Ik denk dat er iets fout is gegaan.
