### ISSUE TITLE
Werkt prima behalve als.. App works fine except...

### ISSUE THREAD

**Issue by RBOUMAN** [robertraaijmakers/com.trashchecker#59]
Hier bij Twentemilieu in Enschede worden soms twee containers geleegd op dezelfde dag. Ik kreeg dus maandag een melding voor de blauwe(papier) kliko op dinsdag terwijl op dezelfde dag ook de groene (gft) geleegd werd.
De app zou bv iets moeten melden dat er meerdere klikos geleegd worden

Here with Twentemilieu in Enschede on some days two containers will be emptied on the same day.. Last mondoy i got a message that the blue kliko would be emptied on Tuesday but on the same day also the green kliko (organics) would be emptied.
The app should ie give a notification the more klikos are to be emptied on the same day

**Comment by robertraaijmakers** [comment]
Added the default speech output to the label when two trash types are collected on the same day. No manual overwrite possible since is won't happen that often for most of the users and a manual overwrite of the label would make it very complex.

This will be released in version 2.6.0.
