### ISSUE TITLE
Address for http://www.mijnafvalwijzer.nl/ doesn't work

### ISSUE THREAD

**Issue by robertraaijmakers** [robertraaijmakers/com.trashchecker#6]

**Comment by rjbaat** [comment]
@robertraaijmakers Sample postcode: 6718MV 11

**Comment by robertraaijmakers** [comment]
Oké, bit strange. It is a bug and I have to figure out why.
But for now, a workaround seems to be if you:
Enter another postal code: e.g. 3436RN 1
Then leave the settings page
Go back
Change the source to: "Unknown"
Enter the given postal code and house number
Hit Save Changes

Then it turns green. When you click on the text you see he retrieves the correct dates... why and how, I yet don't know. But it is working, kinda.

**Comment by Veldkornet** [comment]
I found the same (putting it on unknown and then pushing save). Although it springs to a different each time. And then if you push save again (on the one that it selected, it fails again.

**Comment by robertraaijmakers** [comment]
After updating the app and resetting the settings, this issue should be solved. Please follow the instructions in this comment if the reset doesn't work directly: https://forum.athom.com/discussion/comment/59575/#Comment_59575
