### ISSUE TITLE
Is it ok if I make a new PR with support for Norway?

### ISSUE THREAD

**Issue by PetterRuud** [robertraaijmakers/com.trashchecker#60]
I have created an simple app for myself by reverse engineering Komtek Api in norway (we only have a few providers here).

So instead of making a a new app for Norway, would it be Ok if i just added it to the trashApi?

- Petter

**Comment by robertraaijmakers** [comment]
Hi,

That would be great! Please add it to the beta branch since I did some refactoring lately that isn't available on master yet. But I will merge the pull request in the beginning of September. Currently quite busy!
