### ISSUE TITLE
RWM afvalwijzer

### ISSUE THREAD

**Issue by dwgreven** [robertraaijmakers/com.trashchecker#62]
Hi,
The trashchecker gives a signal on the wrong date. I see in the debug screen with the dates he has taken the dates for 2020 also but with the year 2019 (ex. 08-10-2020 in the debug screen it says 08-10-2019].

Greetings,
Wilfred

**Comment by robertraaijmakers** [comment]
Hi Wilfred,

Which API is selected (below where you enter the postal code) for retrieving the data? I can't see a specific RWM implementation in the app.

With kind regards,
Robert

**Comment by robertraaijmakers** [comment]
Ah, found it, it's in afvalwijzer. I added parsing of the year value as well... should be fixt in release 2.6.2 (now pushed to Athom for review as beta)

**Comment by dwgreven** [comment]
Hi Robert,

I couldn’t see my mail at github, i made a new one at the same time as your mail. Sorry for the inconvenience!
It is RWM afvalwijzer so as you said.
Thanks for solving the problem!

Greetings,
Wilfred
