### ISSUE TITLE
'Last of the month' and unexpected crash

### ISSUE THREAD

**Issue by Neuron44** [robertraaijmakers/com.trashchecker#66]
I like the app!

Unfortunately, the option that the trash is collected on the last monday/tuesday/etc of the month does not seem to pick the correct day. In my case, the paper is collected on the last monday of the month. It currently chose 19-08, 23-09, 21-10 and 18-11.

Also, since the last update, I received an error. I refer to 64f4a3d3-6da6-4901-afd6-75da669904d6.

I hope you find the time to look into to this, because the app is very usefull! Thanks in advance.

**Comment by robertraaijmakers** [comment]
Workaround for the last vs second last is to set the setting to "Second last". This will actually calculate the last monday of the month... Will push a update soon.

**Comment by Neuron44** [comment]
Just tried it and it returned the correct dates. Thank you for the work around.

Let me know if you require additional data regarding the crash

**Comment by robertraaijmakers** [comment]
Should be fixt in new version 2.6.8 currently submitted to the store for approval.
