### ISSUE TITLE
Glas, papier en best option circulus berkel not working

### ISSUE THREAD

**Issue by valkhyr1** [robertraaijmakers/com.trashchecker#68]
The option "Glas, papier en best (boeken, e-goed, speelgoed)" from circulus berkel doesn't work for papier and textiel.

The app does reconize the day with the code "drocodev" for Deventer.

![afval](https://user-images.githubusercontent.com/10817059/67389732-74cf7600-f59b-11e9-97f2-3245a3ad12eb.jpg)

**Comment by robertraaijmakers** [comment]
They keep changing the tags. I added it to the ZWAKRA tag and both ZWAKRA as DROCODEV will be marked as PMD

**Comment by valkhyr1** [comment]
Thanks for the quick response :-)

**Comment by valkhyr1** [comment]
![afval](https://user-images.githubusercontent.com/10817059/69179812-72195f80-0b0c-11ea-9f86-08608109c0dd.jpg)

I'm missing the option "Glas, papier en best" now, now I get option 5 (PMD) with "Glas, papier en best"

**Comment by robertraaijmakers** [comment]
I'm a bit struggling in what categorie to place the 'glass, papier, best'. Supported categories in the app are: papier, textiel, pmd, rest, gft, grof.

So this one falls in both paper and rest. I can add it to textile (just as the zwakra was added earlier). And then you are able to change the word textile via the tag settings to another name... do you have another suggestion?

**Comment by robertraaijmakers** [comment]
zwakra will be logged as PMD
drocodev will be logged as PLASTIC

Via the custom labels you can set the names you want to be displayed in the global tag settings to make the description to your own liking.

Fix will come in version 2.7.0.

**Comment by valkhyr1** [comment]
App version 2.7.1 works for me, but after I remove the old app and install and configure the new version.
The first time after the upgrade, I only get null with the debug screen.
Now I get PLASTIC, GFT, PMD and REST :-)
I saw a little issue, I can't change the label 'GROF VUIL'.

**Comment by robertraaijmakers** [comment]
Good to hear that it is working now! Still wondering why the upgrade of the settings between the old and new version gives that much problems for many users.

I've fixt the grof vuil issue btw, thanks for spotting it!
