### ISSUE TITLE
App receives no data

### ISSUE THREAD

**Issue by maarten236** [robertraaijmakers/com.trashchecker#69]
Great App!

Since a couple of weeks the app stopped working. In Honey app Trashchecker shows the loading-icon continously.

I reinstalled the app without improvements. When I register of change my (or any other) adress the app keeps on searching for the adress.

Really miss the reminders so would be great if you can help.

Reference:
93a822ef-9fe0-4bc2-916f-58e9bd89c312

**Comment by robertraaijmakers** [comment]
Sorry to hear that. I checked the logs but it's empty. What you can try is: remove the app, reboot Homey, install the app again. Then select the correct API that you know supports your address. Then try to see if it finds any data.

If that doesn't work, try sending me a log again and hopefully it contains some data that I can use to debug the issue.

**Comment by maarten236** [comment]
Solution seems to work, the restart did it.
Thanx for your advice!

**Comment by robertraaijmakers** [comment]
Good to hear!
