### ISSUE TITLE
button [sla label op]  save label does not work

### ISSUE THREAD

**Issue by driesk81** [robertraaijmakers/com.trashchecker#71]
when trying to set the global tag settings, tag for today,tomorrow and the day after tomorrow are not saved by the app. Pushing de button [sla label op] has no effect.
I made a flow that puts the value of the global tag in the timeline in the morining of al collection day. This is whats printed. Vandaag worden de oranje container, de blauwe container en de grijze container opgehaald.
The settings for the global tag vandaag are:  plastic: Het plastic wordt vandaag opgehaald. papier: De papier container wordt opgehaald. restafval: De restafval zak wordt opgehaald.
app version v2.6.4 stable. What can i do to solve this problem?

**Comment by robertraaijmakers** [comment]
Sorry for the late reply. The custom label settings aren't applied when multiple type of trash are collected on the same day. And that's the case in your situation.

Because of the multiple types of trash collected on the same day it combines the default container type words in one sentence: Vandaag worden de oranje container, de blauwe container en de grijze container opgehaald.

Before the multi-type of trash support was built-in it only printed one of the labels as global tag which let to frustration of many users. That's why this workaround was created to fall-back to the default text when multiple types of trash are collected on the same day.

**Comment by driesk81** [comment]
Thank you for explaining. Maybe a good thing to clarify this in the app itself. For example in the configuration page.

**Comment by robertraaijmakers** [comment]
That is indeed a good idea. I was still hoping to figure out a way to make sure people can configure it themselves (even with multiple types). But couldn't think of a simple way on how to resolve this (without making the setting screen even more complex).

So I will leave this one open for now to see if I (or anyone else) can come up with a suggestion to make it better :)

**Comment by driesk81** [comment]
Good to hear. My solution for the moment is that i made a variable for every garbage type. Each early morning i check if there is a garbage collection that day, and fill the variables with a text (for example: oud papier) or just a dash. Then i let homey say:  Zet [type 1], [type 2], [type 3], [type 4], [type 5], buiten. I also send a notification in this format. This is quick an dirty but i think using multiple global variables could be a part of the solution.
btw most things ar not complex if you have got a decent manual ;-)

**Comment by robertraaijmakers** [comment]
Should be fixt in new version 2.6.8 currently submitted to the store for approval.

**Comment by driesk81** [comment]
brainfart:

> Because of the multiple types of trash collected on the same day it combines the default container type words in one sentence: Vandaag worden de oranje container, de blauwe container en de grijze container opgehaald.

The oranje contaniner is in my case the bag for plastic waste. the blauwe container is the papier container etc. If it would be possible to change de default container type words as user it is possible to create a logical sentence when multiple garbage types are collected.

**Comment by robertraaijmakers** [comment]
I have a possible fix ready. In the next version (2.7.0) there is an extra option where you can create your own sentence. Some variables in the sentence will be replaced with the words specified for the trash types.

See example below
<img width="449" alt="Screenshot 2020-03-06 at 22 07 54" src="https://user-images.githubusercontent.com/1773099/76122718-05f93380-5ff7-11ea-9ff7-703ac29c46e8.png">
