### ISSUE TITLE
Rova Calender not update for 2020

### ISSUE THREAD

**Issue by jeroendew** [robertraaijmakers/com.trashchecker#73]
The rova calender isn't updating the data for 2020. I only see the december 2019 dates.

**Comment by kay-arne** [comment]
Apparently Rova jumped to another api/ source. I had the old app Rova app still installed on my phone. The old app showed data until December 2019, like Homey (this app) does. 
The new Rova app has the correct data. 

So it seems... new app, new api...

**Comment by robertraaijmakers** [comment]
They indeed changed to a new API: https://inzamelkalender.rova.nl/nl/3811KA/7/ (random postal code & number).

Can't find a JSON variant of this page, maybe someone with the app can see if they can sniff their network traffic to see if the app just displays this page, or that there is an API that can be used?

**Comment by kay-arne** [comment]
I'm no expert at this, but this is wat i found using the app on my Android phone:
http://api.inzamelkalender.rova.nl/webservices/appsinput/?apikey=5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca&method=getVersionV2&postcode=<number><letters>&street=&huisnummer=<number>&toevoeging=&gemeenteName=<city>

But the response seems useless to me:
{"afvalDate":"1578382432","contentDate":"1580724940","iconsDate":"NOK"}

**Comment by robertraaijmakers** [comment]
Should be fixt in new version 2.6.8 currently submitted to the store for approval.

**Comment by kay-arne** [comment]
Cool, thnx 👍
