### ISSUE TITLE
Afvalwijzer doesn’t get a date from “mijn afvalwijzer”

### ISSUE THREAD

**Issue by dwgreven** [robertraaijmakers/com.trashchecker#75]
The app has no dates for collecting the garbage. It is using “mijn afvalwijzer”.
Every date is an “erroneous date”.
Is this app related (or upgrade homey to 4.0.0)?

Thanks for the help,
Wilfred

**Comment by robertraaijmakers** [comment]
Should be fixt in new version 2.6.8 currently submitted to the store for approval.

**Comment by robertraaijmakers** [comment]
Related to #74

**Comment by dwgreven** [comment]
Hi Robert,
Today version to 2.6.12 but the same issue: erroneous date. The app stops working.

Greetings,
Wilfred
