### ISSUE TITLE
Support for Irado?

### ISSUE THREAD

**Issue by LockTar** [robertraaijmakers/com.trashchecker#76]
Is it possible to add support for Irado? 
[https://www.irado.nl/](https://www.irado.nl/)

On the site, you can input your postalcode and housenumber and you get a personal overview.

**Comment by robertraaijmakers** [comment]
Hi, thanks for the request. If your city is not supported you can always add your schedule manually. You can add new cities yourself, but requests to add new cities aren't honoured. If you wish to contribute to the project (for example by adding support for a city). I would advise you to take a look at [this explanation](https://github.com/robertraaijmakers/com.trashchecker/tree/master/developers).

**Comment by LockTar** [comment]
I will check if there is an api. If I can find it, I will make a PR.

**Comment by LockTar** [comment]
Can't find any API in the website code. I think it's rendered server side. Mailing the developer for help right now 👍

**Comment by robertraaijmakers** [comment]
Closed due to inactivity.
