### ISSUE TITLE
See issue 75 erroneous date

### ISSUE THREAD

**Issue by dwgreven** [robertraaijmakers/com.trashchecker#77]
Hi Robert,

Today the app updated to 2.6.12, but the same problem: erroneous date.
Using afvalwijzer. The app is crashing.

Tell me if you need more info.

Greetings,
Wilfred

**Comment by robertraaijmakers** [comment]
Hi Wilfred,

Can you provide a postal & housenumber (just pick a random one that works with afvalwijzer) so that I can try to reproduce this issue?

As I don't see any app crash reports from Athom coming in I have a hard time reproducing the issue.

With kind regards,
Robert

**Comment by dwgreven** [comment]
Hi Robert,

I use mijn afvalwijzer, try postal code 6191 JM housenumber 12

Greetings,
Wilfred

**Comment by dwgreven** [comment]
Hi Robert,
I have the app deleted, homey restarted and install the app.
By configuring the app (postal code, housenumber etc) i click on save and then nothing happened, only the apps isn’t working anymore. See picture.

Greetings Wilfred
![C1C8A3AB-8ACB-4948-A759-E8824FE2B2E9](https://user-images.githubusercontent.com/52658446/75547507-54249a80-5a2b-11ea-8106-4c0d82f3a6d5.png)

**Comment by robertraaijmakers** [comment]
I'm sorry. Have been trying for three hours to fix this but can't even get any debug info from the Homey console. I'm giving up for now, maybe someone else can help fix this issue.

**Comment by dwgreven** [comment]
Hi Robert,

I have de-installed the app, ptp for 15 min. and re-installed the app.
I configure the app with postcode, housenumber and the source of collectordate. Then i click on save and the app goes searching. In that process the app stops working and the field whit dates gives “null”.
I hope this helps you?

Greetings,
Wilfred

**Comment by robertraaijmakers** [comment]
Thanks, I've added a framework to make testing the API's easier. The problem is that now, with the current version in the beta branch the test runs fine and the data is correctly retrieved. However, when running it on the Homey I get multiple memory warnings. Will continue searching another day to see if that's solvable.

**Comment by robertraaijmakers** [comment]
![image](https://user-images.githubusercontent.com/1773099/75805127-7bf46500-5d81-11ea-984b-47e74e097836.png)
Some more information on the issue. I have no clue what is causing this memory boost. But I think it has something to do with the cheerio module.

**Comment by dwgreven** [comment]
Hi Robert,
I saw the same, much memory use and then the app crashed.
Greetings Wilfred
![50D6FE47-0518-4F40-9FD7-2AF73C3DBDA0](https://user-images.githubusercontent.com/52658446/75894118-ab5fac00-5e2b-11ea-813e-54bce4874edf.png)

**Comment by robertraaijmakers** [comment]
The new version can be tested through this link: [com.traschecker](https://homey.app/a/com.trashchecker/test/).

Can you please install this version and check if the fix is working?

**Comment by dwgreven** [comment]
Hi Robert,

I did yesterday an update (app) and the app crashed. This morning i gave homey a restart and the app crashed. I hope the reports will help you further?

Greetings,
Wilfred

**Comment by robertraaijmakers** [comment]
Please try 2.7.1, there was a bug in 2.7.0.

**Comment by dwgreven** [comment]
The notification in the screen is: crashed during loading.

Greetings,
Wilfred

**Comment by dwgreven** [comment]
Hi Robert,

The new version (2.7.1) is installed without crashing.
I filled in the postalcode etc. Became a message in green: adres is aangepast naar...etc.
and by collecting days: null
All the same after a restart of homey.

Greetings,
Wilfred

**Comment by dwgreven** [comment]
Hi Robert,

I saw the new version so i have installed it.
The new version (2.7.2) is installed without crashing.
I filled in the postalcode etc. Became a message in green: adres is aangepast naar...etc.
and by collecting days: null
All the same after a restart of homey, no crash, collecting days: null.

Greetings,
Wilfred

**Comment by robertraaijmakers** [comment]
Thanks for testing this actively. I thought I had fixt the issue with version 2.7.2. What you can try is update to 2.7.3 and then setting the manual settings to " based on api " (and after saving the manual setting, also re-save the normal settings) this should resolve the issue that no dates are rendered.

**Comment by dwgreven** [comment]
Hi Robert,

Yes, its working again! The save and re-save did the trick!
Thanks for your work.

Greetings,
Wilfred
