### ISSUE TITLE
PDM not visible  in "Mijn Blink"

### ISSUE THREAD

**Issue by RobHomey** [robertraaijmakers/com.trashchecker#78]
Hi Robert,

When using source: Mijn Blink, I only see plastic and not PDM.
At my address there is no possibility for only plastic.
"PLASTIC" should be "PDM" and than it is ok.
Can you place change this field?

I have copied the debug from the app:

{
  "GFT": [
    "12-03-2020",
    "09-04-2020",
    "23-04-2020"
  ],
  "PLASTIC": [
    "05-03-2020",
    "12-03-2020",
    "19-03-2020",
    "26-03-2020",
    "02-04-2020",
    "09-04-2020",
    "16-04-2020",
    "23-04-2020",
    "30-04-2020"
  ],
  "REST": [
    "19-03-2020",
    "16-04-2020"
  ],
  "PAPIER": [
    "25-03-2020",
    "22-04-2020"
  ],
  "TEXTIEL": [
    "17-03-2020"
  ]
}

Kind regards,
Rob

**Comment by robertraaijmakers** [comment]
Hi Rob,

Do you have an example postal code and home number that I can use to test?

With kind regards,
Robert

**Comment by RobHomey** [comment]
Hi Robert,

Ja hoor. Je kunt 5673 RE gebruiken en huisnummer 2. 

Groeten,
Rob

**Comment by robertraaijmakers** [comment]
Hi Rob,

Ik heb het even gecontroleerd. Er wordt inderdaad PMD opgehaald, maar die valt in de app onder de categorie "plastic". In de app is geen andere category, dit omdat bij iedereen het net even anders is en er is gekozen om dit onder de noemer PMD te hangen. Via de App Settings kan je de zin aanpassen die in de label van de app komt te staan en daarmee de tekst naar wens aanpassen.

Alle data waarom de PMD opgehaald wordt, wordt dus netjes onder de kop Plastic vastgelegd.

**Comment by robertraaijmakers** [comment]
Sorry, PMD is an own type. Totally forgot, will be fixt in next version for blink.

**Comment by RobHomey** [comment]
Hi Robert,

Thanks for the update. Good to hear that this issue can be fixed.
Will the next update available soon?

Kind regards,
Rob

**Comment by robertraaijmakers** [comment]
The new version can be tested through this link: [com.trashchecker](https://homey.app/a/com.trashchecker/test/).
After some feedback I will publish it as public available in a week or so.

**Comment by RobHomey** [comment]
I have installed the new app but after adding the zip code it looks like the app cannot find the correct address. It stays in: adres checken

**Comment by RobHomey** [comment]
I know why the app cannot read my zip code. 
The app crashes at startup.

**Comment by RobHomey** [comment]
The app works. Only thing I have to sole are the exclamation mark in all my flows.

**Comment by RobHomey** [comment]
Exclamation marks are solved by restarting the Homey app on my iPhone. 
Last question: why do I not see the debug info of the days anymore in the app?

**Comment by robertraaijmakers** [comment]
What do you mean by debug info? Can you make a screenshot of the info you are missing?

**Comment by RobHomey** [comment]
The app is not loading the dates.

**Comment by robertraaijmakers** [comment]
Please try 2.7.1, there was a bug in 2.7.0.

**Comment by RobHomey** [comment]
I know. The screen shot sent is V2.7.1
No data is coming in.

**Comment by robertraaijmakers** [comment]
Found the possible issue, can you retry with version 2.7.3? Thanks :)

**Comment by RobHomey** [comment]
After installation of version 2.7.3, still no data received.

**Comment by robertraaijmakers** [comment]
What you can try is setting the manual settings to " based on api " (and after saving the manual setting, also re-save the normal settings) this should resolve the issue that no dates are rendered.

**Comment by RobHomey** [comment]
I did what you asked but now PDM is gone again.

**Comment by robertraaijmakers** [comment]
That is just very strange. 
Can you try:
1. Uninstall the app
2. Reboot homey
3. Re-install the app (via the test page)
4. Go to settings and verify that no data is visible any more (your postal code & homenumber should be removed and all the app settings should be back to the default settings)
5. Verify that the settings under "manual" are set to " based on API "
6. Re-enter your postalcode & homenumber and check if the data is shown

**Comment by RobHomey** [comment]
I have followed your instructions. 
Sorry to say but no pdm is visible.

**Comment by robertraaijmakers** [comment]
PMD is now reported as PMD if there is a separate plastic category that will be logged in plastic.

**Comment by RobHomey** [comment]
Ok, clear but I do not understand why I do not see PDM. At my address and others (which using the app) make use of PDM and do not have a separate category for plastic. 

 What now see in the app using V2.7.3 is Plastic iso PDM. Is it not possible to change the header Plastic into PDM?

{
  "GFT": [
    "12-03-2020",
    "09-04-2020",
    "23-04-2020",
    "07-05-2020"
  ],
  "PLASTIC": [
    "12-03-2020",
    "19-03-2020",
    "26-03-2020",
    "02-04-2020",
    "09-04-2020",
    "16-04-2020",
    "23-04-2020",
    "30-04-2020",
    "07-05-2020"
  ],
  "REST": [
    "19-03-2020",
    "16-04-2020"
  ],
  "PAPIER": [
    "25-03-2020",
    "22-04-2020"
  ],
  "TEXTIEL": [
    "17-03-2020"
  ]
}

**Comment by RobHomey** [comment]
Robert, it looks like that V2.7.4 solved the PDM issue. It seems to be ok and the correct dates are displayed. 
Good work 👍🏻👌🏻

**Comment by robertraaijmakers** [comment]
Good to hear!

**Comment by RobHomey** [comment]
Hi Robert,

Today is “afval ophaal dag” in my street. I can confirm that the app is working 100%. No issues.
A smal remark before you launch the new update. There are two small typo’s in the text. Maybe you can correct it beforehand. I changed it myself.

The text at the section PDM:

“De plastic, metalen en drankcartons" 

Should be:

"Het plastic, metalen en drankkartons"

Thanks for the support.

Kind regards,
Rob
