### ISSUE TITLE
Sinds update werkt hij niet meer

### ISSUE THREAD

**Issue by henkbart** [robertraaijmakers/com.trashchecker#81]
Sinds de laatste update werkt de app niet meer. Hij leest geen data meer in.
Als je hem opnieuw wilt instellen voor de correcte verwerker, geeft hij aan dat het adres ongeldig is.

**Comment by robertraaijmakers** [comment]
Wat is de versie van de app die je gebruikt? Kan je eventueel deze test versie installeren: https://homey.app/a/com.trashchecker/test/

**Comment by henkbart** [comment]
Ik gebruik versie 2.6.12


------ Original Message ------

**Comment by henkbart** [comment]
Hallo,

Heb deze testversie geinstalleerd, en volgens mij werkt het nu weer 
zoals het moet.

Henk

------ Original Message ------
