### ISSUE TITLE
Mijn afvalwijzer geen data meer naar nieuwe update

### ISSUE THREAD

**Issue by sneekerzzz** [robertraaijmakers/com.trashchecker#82]
Sinds de laatste update werkt de mijn afvalwijzer data niet
Debug geeft geen foutmelding maar er zijn geen datums aanwezig

**Comment by robertraaijmakers** [comment]
Can you provide a screenshot of the manual setting part of the setting page?

The setting should be on "based on API"

**Comment by sneekerzzz** [comment]
Sure,

It's trying to receive data but then null appears.

![Screenshot_20200312-223719](https://user-images.githubusercontent.com/16738330/76568976-4e5e9880-64b2-11ea-92cf-4c63e0ca3e2a.png)
![Screenshot_20200312-223711](https://user-images.githubusercontent.com/16738330/76568982-53234c80-64b2-11ea-9894-aa2b1b53e49e.png)

**Comment by robertraaijmakers** [comment]
The settings seem to be fine. Can you provide a example postal code and house number that I can use to test the afvalwijzer API?

**Comment by larsnet** [comment]
I have the same issue with the latest version.

**Comment by sneekerzzz** [comment]
Thx for looking into this. 
Postal code: 4707re 1

**Comment by robertraaijmakers** [comment]
Thanks for the examples. Can you please test with this new version here: https://homey.app/a/com.trashchecker/test/

**Comment by larsnet** [comment]
With the new version i have dates again, so seems to work.
