### ISSUE TITLE
Every 4th is not supported

### ISSUE THREAD

**Issue by JordVisbeen** [robertraaijmakers/com.trashchecker#83]
Hi, at my place paper is collected every 4th Saturday of the month. Unfortunately this cannot be selected in the app. It's every last or second last. But the 4th Saturday of the month is sometimes last and sometimes second last.
Can this be added to the manual option list?
Thanks!
![Screenshot_20200104-143525](https://user-images.githubusercontent.com/62200522/76698098-1b2d2c80-669f-11ea-90fd-c49f521d8818.png)

**Comment by robertraaijmakers** [comment]
Thanks, thought that there wasn't always a fourth week (which is true for February), so thought that collectors wouldn't use that. But added it now, will be available in next update.

**Comment by JordVisbeen** [comment]
Thank you!
