### ISSUE TITLE
Den Bosch not working (with possible solution)

### ISSUE THREAD

**Issue by joostvkempen** [robertraaijmakers/com.trashchecker#84]
When setting up my adress voor 'Den Bosch Afvalstoffendienstkalender' there's an error: not available for this adress. I've tried multiple adresses in Den Bosch, but all the same. I'm not a developer so don't know how to change the code, but I can do a little debugging. The following might be a solution, but I'm not sure and have not tested this.

Looked into the code and noticed that for the other 'generalAfvalwijzer' the URL is always without the prefix http ór with prefix https. Den Bosch is the only one with 'http'. When searching for the website Afvalstoffendienstkalender it forces to https when trying to visit http. Could the api fail because of the missing security?

Hope you can fix this? I'm willing to test. Or you could tell me how to change the code ?

**Comment by robertraaijmakers** [comment]
Thanks for reporting. Will release the fix soon, the general implementation isn't that general as it seems. Every provider uses its own layout, so had to create a fix for Den Bosch which is using a different layout for the website then other providers.

**Comment by robertraaijmakers** [comment]
The new version is available for test here: https://homey.app/a/com.trashchecker/test/

**Comment by joostvkempen** [comment]
Downloaded the test-version: my adress is accepted and there is data in the debug section. Have to wait until next wednesday for the real test ;-)
