### ISSUE TITLE
Type of trash not mentioned correctly in tag

### ISSUE THREAD

**Issue by rpbras** [robertraaijmakers/com.trashchecker#85]
I have to use the manual input for the collection days because my postal code is not supported. The app does recognize on which day trash is collected, but on that day the tag says ' er wordt vandaag geen kliko geleegd'.
The debug information also doesn't show any dates. Before the update everything worked well. Any idea how to solve this?
Kind regards, Raymond

**Comment by robertraaijmakers** [comment]
Hi, can you share a sceenshot of your manual settings page? Also, have you tried to change some settings on the page and re-save it?

With kind regards, Robert

**Comment by rpbras** [comment]
Here are the screenshots. And I tried several times to change setting and to save them. That didn't solve the problem. Thanks in advance.

Kind regards,
Raymond 
![Screenshot_20200328-060123_Homey](https://user-images.githubusercontent.com/36108093/77815488-d43a3080-70bb-11ea-8011-4074615e42b0.jpg)
![Screenshot_20200328-060136_Homey](https://user-images.githubusercontent.com/36108093/77815491-d603f400-70bb-11ea-85de-4f339f5b27e0.jpg)

**Comment by rpbras** [comment]
I tried to install the latest beta version, but it crashes immediately.

**Comment by rpbras** [comment]
Solved by using the command : 'npm install dateformat' in the command prompt.

**Comment by robertraaijmakers** [comment]
Can you try to install it from https://homey.app/nl-nl/app/com.trashchecker/Afval-Herinnering-2.0/test/ ? I think the issues should be resolved now.

**Comment by rpbras** [comment]
> Can you try to install it from https://homey.app/nl-nl/app/com.trashchecker/Afval-Herinnering-2.0/test/ ? I think the issues should be resolved now.

Robbert, it works. Thnx for all your effort!!
