### ISSUE TITLE
Address not supported

### ISSUE THREAD

**Issue by RobHomey** [robertraaijmakers/com.trashchecker#88]
![C4C2F21F-0AF8-43EC-96C9-8336CBA68DFA](https://user-images.githubusercontent.com/61829624/78724315-744e5000-792d-11ea-8b8c-6eae7090b86e.png)
Hi Robert,
After update 2.7.9 the app is not supporting my address anymore by selecting Mijn Blink.
Is there a way I can go back to the previous version because I had no issues with it.

**Comment by RobHomey** [comment]
Hi Robert,

I don't know why but almost 24 hours after update 2.7.9 my address is working again and I see in the debug info the date again.

**Comment by robertraaijmakers** [comment]
Probably some issues at Mijn Blink website, glad it is working again!
