### ISSUE TITLE
Dag te vroeg

### ISSUE THREAD

**Issue by michielkrijger** [robertraaijmakers/com.trashchecker#89]
Ondanks het correct invullen van datum bij handmatige invoer, geeft de app telkens een dag te vroeg de waarschuwing. Dit wordt ook in het overzicht verkeerd weergegeven.

**Comment by robertraaijmakers** [comment]
Zou je een screenshot kunnen maken van de handmatige invoer, van het debug menu onderaan, en de plek waarin je aangeeft dat het een dag te vroeg staat? (Misschien dat die laatste twee hetzelfde zijn, dat weet ik niet). Graag ook de versie waar je Homey op draait, en de versie van de trashcan app zelf die je gebruikt. Dan kan ik gericht met je meedenken.

**Comment by michielkrijger** [comment]
![2AC07BA2-7B9C-4D9D-B5F2-A1D0CAE9F3A8](https://user-images.githubusercontent.com/63420319/78929092-0f683680-7aa2-11ea-8e3b-b6ede86d2051.png)
![975B55AD-6E5E-47A8-9FEB-D26BC96DFD62](https://user-images.githubusercontent.com/63420319/78929098-12632700-7aa2-11ea-8e8c-1c214f0af128.png)
Had net de invoer opnieuw ingevoerd vanaf vandaag. Nu lijkt het goed te staan in het debugoverzicht. Wel opvallend dat er ook dagen vóór de nieuwe invoer nog bij staan. Of zijn dat oude?

**Comment by robertraaijmakers** [comment]
Hij rekent bij handmatige invoer, voor de zekerheid, 2 weken terug + 2 weken voorruit. Zo in het debug overzicht lijkt alles nu gewoon goed te staan. In de laatste update van de app zijn er diverse wijzigingen doorgevoerd op de handmatige invoer en de afhandeling daarvan (zie ook issue #85). Ik ga er dan ook even vanuit dat met deze update ook dit issue verholpen is. Mochten er nog problemen zijn dan hoor ik dat graag.
