### ISSUE TITLE
PD instead of PMD in Nuland (Den Bosch)

### ISSUE THREAD

**Issue by Whireking** [robertraaijmakers/com.trashchecker#90]
The retrieving of plastic and drink carton doesn't show up in Homey for the village I live in.
I checked https://denbosch.afvalstoffendienstkalender.nl and saw that the trash data is called 'pd' instead of 'pmd' or 'plastic'. 
Is it possible to have pd included in the trash checker? At least under plastic of pmd?

```
<a href="#waste-pd" class="wasteInfoIcon textDecorationNone" title="Plastic Drankkartons"><p class="pd">vrijdag 17 januari<br />
<span class="afvaldescr">Plastic Drankkartons</span></p></a>

```

**Comment by robertraaijmakers** [comment]
Will be published when next update is pushed.

**Comment by Whireking** [comment]
Thank you!
