### ISSUE TITLE
Afvalkalender Meerlanden

### ISSUE THREAD

**Issue by roelfsre** [robertraaijmakers/com.trashchecker#92]
Hallo,

Na de laatste update werkt de afvalherinnering niet meer voor mij. 
Ik maak gebruik van Meerlanden, maar als ik mijn postcode invoer, dan wordt deze niet herkend.
Doe ik iets fout ?
Als je meer informatie nodig hebt, dan hoor ik het graag.

Mvg. René

**Comment by robertraaijmakers** [comment]
Zou je het kunnen controleren met de laatste test versie (2.8.0) die hier te downloaden is? https://homey.app/a/com.trashchecker/test/

Als dat niet werkt dan ontvang ik graag een postcode + fictief huisnummer (die wel bestaat in de straat natuurlijk) zodat ik het zelf even kan testen.

**Comment by roelfsre** [comment]
Beste Robert,

Bedankt voor je hulp. Helaas werkt het nog niet met de laatste versie. Je kan het proberen met postcode 2134pj en huisnummer 105
Afvalkalender Meerlanden.

Nogmaals bedankt voor je hulp.

Mvg. René

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by robertraaijmakers** [comment]
Found the issue, they switched providers. Luckily one that was used by others, so it was a relatively easy switch. Can you try again?

https://homey.app/a/com.trashchecker/test/

**Comment by roelfsre** [comment]
Yes ! It works again ! Thank you very much !

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Munnikie** [comment]
Hoi Robert,

Ik begrijp dus goed dat het probleem voor Meerlanden gefixed is in de laatste versie? Wanneer wordt deze via Homey app store geupdated?

Grt!

**Comment by robertraaijmakers** [comment]
Hij zou nu live moeten staan! Sorry voor de vertraging
