### ISSUE TITLE
Den Haag

### ISSUE THREAD

**Issue by zeuslooye** [robertraaijmakers/com.trashchecker#93]
Hoi 

Kan je toevallig ook Den Haag toevoegen aan de App??

https://www.denhaag.nl/nl/afval/huisvuilkalender.htm

Gr
Jeroen

**Comment by robertraaijmakers** [comment]
Ikzelf implementeer geen API's omdat het mij niks oplevert buiten een hoop onderhoud en bugs. Er zijn goede handmatige opties.

Ik zal deze wens hier open laten staan, misschien dat meer mensen zich aansluiten en iemand treft die handig is met een beetje code. Je kan natuurlijk ook altijd een berichtje plaatsen op het forum in de Homey community om te kijken of je daar een groter bereik hebt.

**Comment by robertraaijmakers** [comment]
@zeuslooye het heeft even geduurd, maar door @HugoKNL kan je nu Den Haag automatisch uitlezen. Een test versie is hier te downloaden: https://homey.app/a/com.trashchecker/test/. De algemene versie zal binnenkort ook voor iedereen beschikbaar komen.
