### ISSUE TITLE
Featurerequest: get calendar entries for the upcoming 7 days

### ISSUE THREAD

**Issue by walter-wm3** [robertraaijmakers/com.trashchecker#95]
Hallo Robert

is het mogelijk om de app uit te breiden zodat niet alleen de entries van vandaag, morgen en overmorgen opgehaald worden maar van de komende 7 dagen. Achterliggende gedachte is dat ik vrijdags graag wil weten welk afval op welke dag van de komende week wordt opgehaald zodat ik kan bepalen of ik afval dat de komende week niet wordt opgehaald, zelf moet wegbrengen.

thnx voor je reactie.

Gr. Walter

**Comment by robertraaijmakers** [comment]
Hi Walter,

Op dit moment staat dit niet op de planning om deze feature toe te voegen.
Ik laat hem open staan voor het geval er meer gegadigden zijn.

Mvg, Robert

**Comment by robertraaijmakers** [comment]
Gesloten ivm geen verdere animo & complexiteit om dit op een uniforme manier te realiseren.
