### ISSUE TITLE
Homey spraak klopt niet

### ISSUE THREAD

**Issue by ChillXXL** [robertraaijmakers/com.trashchecker#96]
Top app! Kleine bug denk ik. Bij vraag aan homey;" wanneer wordt mijn grijze container opgehaald?" Krijg ik terug: ....as dinsdag. De datum in de json is juist met '2020-07-14'

Dit is echter geen aankomende dinsdag, maar de week er op op dinsdag. (Vandaag is 4 juli). 
De spraakuitkomst is dus een week te vroeg.

**Comment by robertraaijmakers** [comment]
Hi, gebeurd dit vaker?
Mijn vermoeden is dat de container ook op 2020-07-07 opgehaald werd. Kan je kijken of dit nog steeds voorkomt als je het vraagt?
En zo ja, kan je dan een volledig dump maken van de data dat afval opgehaald wordt en/of een voorbeeld postcode + huisnummer aanleveren?

**Comment by robertraaijmakers** [comment]
Gesloten door inactiviteit.
